### ISSUE TITLE
AttributeError: 'Affiliation' object has no attribute 'affilname'

### ISSUE THREAD

**Issue by langongjin** [pybliometrics-dev/pybliometrics#105]
AttributeError: 'Affiliation' object has no attribute 'affilname'. 

I did not find the same error messages

Thanks!

**Comment by Michael-E-Rose** [comment]
Yes, this could be a bug.  Can you give the exact code that created this bug?  In particular, the Scopus ID is necessary.  Also, what's the version that you use?

**Comment by langongjin** [comment]
hi, sorry for late.
Here is the piece of code where had the error.
```
def clean_affiliation(name):
    name = unicode(name).title()
    pairs = [
        ['University', 'U'],
        ['Universitat', 'U'],
        ['Laboratories', 'Lab'],
        ['Laboratory', 'Lab'],
        ['National', 'Nat'],
        ['Corporation', 'Corp'],
        ['Technology', 'Tech'],
        ['Institute', 'Inst'],
    ]
    
    for needle, replacement in pairs:
        name = name.replace(needle, replacement)
    return name

plot_statistic(lambda p: set(clean_affiliation(a.affilname) for a in p.affiliations))
```
I do not know the version this moment because I cannot run the code out of the university. But I think it should be the latest version because I install it with `pip install pybliometrics`

**Comment by Michael-E-Rose** [comment]
Hi again!  This code doesn't help me to find the bug.  I don't know a) which class and property and b) which item ID you're using.
Can you provide that as well, please?

**Comment by Michael-E-Rose** [comment]
Closed due to inactivity
