### ISSUE TITLE
ScopusSearch breaks if explicitly pass download_results

### ISSUE THREAD

**Issue by fredson** [pybliometrics-dev/pybliometrics#107]
ScopusSearch masks some kw-arguments you could choose to pass on to Search, see (my :-) ) pr https://github.com/pybliometrics-dev/pybliometrics/pull/106 .

While solving the above should do no harm, the following is a bit more tricky:

This fails:
`s = ScopusSearch("Key (gene expression)", max_entries=2000000, download=False, download_results=False)`

stating:

`TypeError: __init__() got multiple values for keyword argument 'download_results'`

Depending on the way you fix that code might break, because ScopusSearch and Search use different keywords. (e.g. renaming the kw download to download_results as in Search).

Maybe one could insert an assertion that fails if download and download_results are both passed and differ.

**Comment by Michael-E-Rose** [comment]
Oh yes, this is indeed something that should be handled.  Thanks for raising awareness!
