### ISSUE TITLE
"'fname' is not defined" error after not adding Authtoken

### ISSUE THREAD

**Issue by katrinleinweber** [pybliometrics-dev/pybliometrics#110]
Hello and thanks for publishing this tool!

I just tried the [ScopusSearch example](https://pybliometrics.readthedocs.io/en/stable/examples/ScopusSearch.html) with Python 3.7.4 installed on Windows 8.1, applied the "issue pybliometrics.scopus.utils.create_config() to start" advice and pasted my API Key.

At the "Authtoken authentication", I "press[ed] Enter" and this was returned.

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\pybliometrics\scopus\utils\create_config.py", line 44, in create_config
    print("Configuration file successfully created at {}".format(fname))
NameError: name 'fname' is not defined
```

However, the config file looks OK, and the examples run fine.

**Comment by Michael-E-Rose** [comment]
I guess this one was fixed with #108.  It's just not live yet.  But the development version is already functional.

**Comment by Michael-E-Rose** [comment]
The patch is live in 2.1.3

**Comment by katrinleinweber** [comment]
Ah, OK! I searched for `NameError` and only found another, apparently unrelated issue. Thanks for https://github.com/pybliometrics-dev/pybliometrics/commit/35a2bae54f524194616c733678a4064af324244b :-)
