### ISSUE TITLE
EID is None in returned results, causing KeyError. 

### ISSUE THREAD

**Issue by jdagdelen** [pybliometrics-dev/pybliometrics#115]
This issue is just in case others run into this and are not aware that @Michael-E-Rose is working on adding functionality to handle these errors. It is discussed in #111 and #114. If you need a temporary fix that ignores entries without EIDs, you can use one of those forks.

**Typical error message looks as follows:** 

s = robust_query('af-id(60015815) AND PUBYEAR > 2017')
df = pd.DataFrame(pd.DataFrame(s))
Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-575f7f96be44>", line 1, in <module>
    df = pd.DataFrame(pd.DataFrame(s.results))
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\pybliometrics\scopus\scopus_search.py", line 87, in results
    authkeywords=item.get('authkeywords'), eid=item['eid'],
KeyError: 'eid'

**Comment by katrinleinweber** [comment]
Could this maybe be some kind of Scopus-internal way to enforce the 5k items download limit? I think I remember that the error started when my queries yielded more results.

**Comment by Michael-E-Rose** [comment]
We experimented a lot with this, I found no consistent pattern.  Moreover, a cursor field may also be missing, which is really annoying because we need it to get information.  And that's really a field that is not related to the number of remaining queries.

A solution for your guys will come this week.

**Comment by katrinleinweber** [comment]
Works fine [now](https://github.com/pybliometrics-dev/pybliometrics/releases/tag/2.2), thank you :-)
