### ISSUE TITLE
Add topic: scopus

### ISSUE THREAD

**Issue by katrinleinweber** [pybliometrics-dev/pybliometrics#118]
I think this would be better findable, if displayed on [GitHub.com/topics/scopus](https://github.com/topics/scopus), please consider [adding that topic](https://help.github.com/articles/about-topics/) to this repo. Thank you :-)

**Comment by Michael-E-Rose** [comment]
Thanks for the hint!

**Comment by katrinleinweber** [comment]
You're welcome :-)
