### ISSUE TITLE
subtypeDescription not passed through

### ISSUE THREAD

**Issue by katrinleinweber** [pybliometrics-dev/pybliometrics#119]
[`subtype` is](https://github.com/pybliometrics-dev/pybliometrics/search?q=subtype), but [`subtypeDescription` isn't](https://github.com/pybliometrics-dev/pybliometrics/search?q=subtypeDescription), although specified in [Scopus' API views](https://dev.elsevier.com/guides/ScopusSearchViews.htm).

**Comment by Michael-E-Rose** [comment]
Might be I missed it, or it's a new field.

Do you want to try yourself first?

**Comment by katrinleinweber** [comment]
Yeah, but it could take a few weeks. Teaching & holidays are coming up. I'll start a PR as soon as I have at least tried something.

If it's needed by anyone else urgently, please don't wait for me.

**Comment by katrinleinweber** [comment]
[Started here](https://github.com/pybliometrics-dev/pybliometrics/compare/master...katrinleinweber:119-subtypeDescription), but it's still lacking tests, which I can only properly add at the office with the Scopus subscriptions.

**Comment by Michael-E-Rose** [comment]
Hi Katrin, any chance you can finish this by the end of this month?  If not, let me know, then I do it.
I'd like to release a new version before November.

**Comment by katrinleinweber** [comment]
Please take over. I'll not manage to get into Python testing in time.

**Comment by Michael-E-Rose** [comment]
Thanks, it's done. For some reason I couldn't push to your fork. Therefore I merged your changes and finalized the tests in another commit.
