### ISSUE TITLE
Get citedby articles

### ISSUE THREAD

**Issue by VJalili** [pybliometrics-dev/pybliometrics#124]
The `ScopusSearch` class returns the **number** of articles citing a given article: 

https://github.com/pybliometrics-dev/pybliometrics/blob/dabf3ef9000cd80f022da6e1c069d9a3a95b8d45/pybliometrics/scopus/scopus_search.py#L93

Is there any method or Scopus API that returns the **list** of these articles?

**Comment by Michael-E-Rose** [comment]
Yes and no. You would have to make another query like "REF(xxx)".

**Comment by VJalili** [comment]
Any examples?

**Comment by Michael-E-Rose** [comment]
Well, if 2-s2.0-84981347698 is the paper whose citing papers you're interested in, you use the ScopusSearch class with the query `REF(2-s2.0-84981347698)`.

https://pybliometrics.readthedocs.io/en/stable/examples/ScopusSearch.html describes how to continue then.
