### ISSUE TITLE
The requestor is not authorized to access the requested view or fields of the resource

### ISSUE THREAD

**Issue by Keramatfar** [pybliometrics-dev/pybliometrics#126]
I have coded a gui for searching in Scopus. The problem is that the program works on my pc but when i run it on another pc in the same pc, by the same api key, i get the following error.

**Comment by Michael-E-Rose** [comment]
See https://pybliometrics.readthedocs.io/en/stable/tips.html#error-messages.
You're not in the right network.

May I ask: How does the GUI look like?

**Comment by jgcaffari1** [comment]
I'm getting this error when connected to my university network through a VPN.  Are there additional steps vpn users need to to take when working remotely?

**Comment by Michael-E-Rose** [comment]
Usually not, but sometimes you need to set a different IP range. This is the case even when you can use Scopus.com normally (such as viewing an abstract). Often your librarians and IT administrators can help.

**Comment by jachicaiza** [comment]
> Usually not, but sometimes you need to set a different IP range. This is the case even when you can use Scopus.com normally (such as viewing an abstract). Often your librarians and IT administrators can help.
 
Could you say me what ports and servers should be open?. I am trying to use the API from home and I received this message. The IT administrators of my university ask me this information to enable the channel.

Thanks

**Comment by jgcaffari1** [comment]
I resolved this issue by getting an 'Institutional Token' from the journal.  However, I am not sure that this is a long term fix.

**Comment by jachicaiza** [comment]
> I resolved this issue by getting an 'Institutional Token' from the journal. However, I am not sure that this is a long term fix.

Thank you.

**Comment by Michael-E-Rose** [comment]
I think it is a good long-term solution. Scopus created this on purpose. pybliometrics asks for an InstToken in the second step of `pybliometrics.scopus.utils.create_config()`. If it doesn't work, please create a new issue.

**Comment by Young1993** [comment]
> I'm getting this error when connected to my university network through a VPN. Are there additional steps vpn users need to to take when working remotely?

Me too, how to solve it

**Comment by Michael-E-Rose** [comment]
Dear @Young1993, this is a closed issue because it has a solution. If the provided solution doesn't work, please create a new issue.

**Comment by umsi-amadaman** [comment]
how do we get an institutional token?  Do we have to email integrationsupport@elsevier.com or is there another way to do this.

**Comment by Michael-E-Rose** [comment]
That's the way
