### ISSUE TITLE
abstract texts from Scopus

### ISSUE THREAD

**Issue by vishalmhjn** [pybliometrics-dev/pybliometrics#130]
I am trying to obtain the abstract texts from Scopus. The thing is that pybliometrics call is not working on executing following code:

```
from pybliometrics.scopus import AbstractRetrieval
ab = AbstractRetrieval(identifier="1-s2.0-S0740624X15000908", view='META_ABS', id_type='eid')
```

The error is `Scopus401Error: The requestor is not authorized to access the requested view or fields of the resource`

On running the Scopus API, I get the expected response:

```
X_ELS_APIKey = 'some_api'  #API Key
url = 'https://api.elsevier.com/content/article/eid/1-s2.0-S0740624X15000908'
headers = {'X-ELS-APIKey': X_ELS_APIKey, 'Accept': 'application/json'}
query = '?query=&view=META_ABS'
r = requests.get(url + query, headers=headers)
```

On another note, `view=META_ABS` is shown to be unrestricted at [https://dev.elsevier.com/guides/AbstractRetrievalViews.htm](url), but that doesn't seem to be the case. This is because all the abstract texts are not accessible with META_ABS. Only the ones with 'full-text' tag are available. Do you know how to get the abstract texts for all the eids?

**Comment by Michael-E-Rose** [comment]
The error message in fact states it all: You are not authorized to access the view.  See https://pybliometrics.readthedocs.io/en/stable/tips.html#error-messages "pybliometrics.scopus.exception.Scopus401Error: UNAUTHORIZED". If your institution is not subscribing to Scopus, try using `subscriber=False`. pybliometrics then automatically assigns the free views.

Also, `1-s2.0-S0740624X15000908` is an EID type I have not seen before. Are you sure it shouldn't have a leading 2? If yes, it might also explain why you're not able to see the document.

Usually the properties `.abstract` and `.description` get you the abstract _if it exists_. Do you have an example of a document where the abstract exists (in Scopus) but the ScopusAbstract() object with `view="META_ABS"` isn't returning the abstract?

**Comment by vishalmhjn** [comment]
`subscriber =False` is not valid for `AbstractRetrieval` function. The thing is I am able to get the response using the basic Scopus methods (using the same network and Key) with the following response:

`{'full-text-retrieval-response': {'coredata': {'prism:url': 'https://api.elsevier.com/content/article/pii/S0740624X15000908',
   'dc:identifier': 'doi:10.1016/j.giq.2015.07.005',
   'eid': '1-s2.0-S0740624X15000908',
   'prism:doi': '10.1016/j.giq.2015.07.005',
   'pii': 'S0740-624X(15)00090-8',
   'dc:title': 'One way traffic: The open data initiative project and the need for an effective demand side initiative in Ghana ',
   'prism:publicationName': 'Government Information Quarterly',
   'prism:aggregationType': 'Journal',
   'prism:issn': '0740624X',
   'prism:volume': '32',
   'prism:issueIdentifier': '4',
   'prism:startingPage': '419',
   'prism:endingPage': '428',
   'prism:pageRange': '419-428',
   'prism:number': '4',
   'dc:format': 'application/json',
   'prism:coverDate': '2015-10-31',
   'prism:coverDisplayDate': 'October 2015',
   'prism:copyright': 'Copyright © 2015 Elsevier Inc. All rights reserved.',
   'prism:publisher': 'Elsevier Inc.',
   'dc:creator': [{'@_fa': 'true', '$': 'Ohemeng, Frank L.K.'},
    {'@_fa': 'true', '$': 'Ofosu-Adarkwa, Kwaku'}],
   'dc:description': "\n               Abstract\n               \n                  In recent years the necessity for governments to develop new public values of openness and transparency, and thereby increase their citizenries' sense of inclusiveness, and their trust in and confidence about their governments, has risen to the point of urgency. The decline of trust in governments, especially in developing countries, has been unprecedented and continuous. A new paradigm that signifies a shift to citizen-driven initiatives over and above state- and market-centric ones calls for innovative thinking that requires openness in government. The need for this new synergy notwithstanding, Open Government cannot be considered truly open unless it also enhances citizen participation and engagement. The Ghana Open Data Initiative (GODI) project strives to create an open data community that will enable government (supply side) and civil society in general (demand side) to exchange data and information. We argue that the GODI is too narrowly focused on the supply side of the project, and suggest that it should generate an even platform to improve interaction between government and citizens to ensure a balance in knowledge sharing with and among all constituencies.\n               \n            ",
   'openaccess': '0',
   'openaccessArticle': False,
   'openaccessType': None,
   'openArchiveArticle': False,
   'openaccessSponsorName': None,
   'openaccessSponsorType': None,
   'openaccessUserLicense': None,
   'dcterms:subject': [{'@_fa': 'true', '$': 'Developing countries'},
    {'@_fa': 'true', '$': 'Ghana'},
    {'@_fa': 'true', '$': 'Open data'},
    {'@_fa': 'true', '$': 'Supply'},
    {'@_fa': 'true', '$': 'Demand'}],
   'link': [{'@href': 'https://api.elsevier.com/content/article/pii/S0740624X15000908',
     '@rel': 'self',
     '@_fa': 'true'},
    {'@href': 'https://www.sciencedirect.com/science/article/pii/S0740624X15000908',
     '@rel': 'scidir',
     '@_fa': 'true'}]},
  'scopus-id': '84939488299',
  'scopus-eid': '2-s2.0-84939488299',
  'link': {'@href': 'https://api.elsevier.com/content/abstract/scopus_id/84939488299',
   '@rel': 'abstract'},
  'originalText': {'xocs:doc': {'xocs:meta': {'xocs:open-access': {'xocs:oa-article-status': {'@is-open-access': '0',
       '@is-open-archive': '0'}},
     'xocs:available-online-date': {'@yyyymmdd': '20150810',
      '$': '2015-08-10'}}}}}}`

Then why should pybliometrics raise an Authorization error?
Regarding the second point, I don't know which "2" are you referring to, but this is a valid eid and you can see the response at [https://api.elsevier.com/content/article/eid/1-s2.0-S0740624X15000908](url).

I have lot of examples where abstract is visible on the website, but not through API. For instance, the abstract for this article is available at [https://www.scopus.com/record/display.uri?eid=2-s2.0-84995946032&origin=inward&txGid=2f50d06c525d6275ae2b91bdd5bbb096](url). The default view returns the response `{'abstracts-retrieval-response': {'affiliation': {'affiliation-city': 'Sophia Antipolis',
   'affilname': 'IDRAC Business School',
   'affiliation-country': 'France'},
  'coredata': {'srctype': 'p',
   'eid': '2-s2.0-84995946032',
   'prism:coverDate': '2014-01-01',
   'prism:aggregationType': 'Conference Proceeding',
   'prism:url': 'https://api.elsevier.com/content/abstract/scopus_id/84995946032',
   'subtypeDescription': 'Conference Paper',
   'dc:creator': {'author': [{'ce:given-name': 'Samy',
      'preferred-name': {'ce:given-name': 'Samy',
       'ce:initials': 'S.',
       'ce:surname': 'Guesmi',
       'ce:indexed-name': 'Guesmi S.'},
      '@seq': '1',
      'ce:initials': 'S.',
      '@_fa': 'true',
      'affiliation': {'@id': '116248731',
       '@href': 'https://api.elsevier.com/content/affiliation/affiliation_id/116248731'},
      'ce:surname': 'Guesmi',
      '@auid': '35210179000',
      'author-url': 'https://api.elsevier.com/content/author/author_id/35210179000',
      'ce:indexed-name': 'Guesmi S.'}]},
   'link': [{'@_fa': 'true',
     '@rel': 'self',
     '@href': 'https://api.elsevier.com/content/abstract/scopus_id/84995946032'},
    {'@_fa': 'true',
     '@rel': 'scopus',
     '@href': 'https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&scp=84995946032&origin=inward'},
    {'@_fa': 'true',
     '@rel': 'scopus-citedby',
     '@href': 'https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&scp=84995946032&origin=inward'}],
   'prism:publicationName': '19th Symposium of the Association Information and Management 2014, AIM 2014',
   'source-id': '21100786320',
   'citedby-count': '0',
   'subtype': 'cp',
   'dc:title': 'Open data, big data and crowdsourcing: Emergent mobile apps business models Open data, big data et crowdsourcing : Les business models émergents des applications mobiles',
   'openaccess': None,
   'openaccessFlag': None,
   'dc:identifier': 'SCOPUS_ID:84995946032',
   'dc:publisher': 'Association Information and Management'}}}`

But the `view = META_ABS` raises `{'service-error': {'status': {'statusCode': 'AUTHORIZATION_ERROR',
   'statusText': 'The requestor is not authorized to access the requested view or fields of the resource'}}}`

**Comment by Michael-E-Rose** [comment]
I looked deeper into the issues you raised.

1. My guess is your subscription doesn't allow for certain views via the API. Therefore I cannot replicate your error:
```
>>> from pybliometrics.scopus import AbstractRetrieval
>>> ab = AbstractRetrieval(identifier="1-s2.0-S0740624X15000908", view='META_ABS', id_type='eid')
>>> ab.title
'One way traffic: The open data initiative project and the need for an effective demand side initiative in Ghana'
>>> ab = AbstractRetrieval(identifier="1-s2.0-S0740624X15000908", view='FULL', id_type='eid')
>>> ab.title
'One way traffic: The open data initiative project and the need for an effective demand side initiative in Ghana'
```

2. Yes, you are right, it's a totally valid EID. I've just not seen an EID starting with 1 instead of 2.

3. Abstracts are sometimes, due to the way Scopus structures the field, available via the property `.description` (as the docs state as well, and as indicated in your code output):

```
>>> ab = AbstractRetrieval("2-s2.0-84995946032")
>>> ab.description
"The aim of this paper is to discuss the business model of a free social GPS mobile app for public transportation. The app functioning relies on open data and crowdsourcing. The crossing of transporter data (open data) and service users' data (crowdsourcing) feed the app's algorithm, which in the end enhance the public transportation experience. The hinge and tensions between for profit and not for profit sides of the data stemming from open data and crowdsourcing are questioned in the implementation of the company business model."
>>> ab.abstract
```

**Comment by vishalmhjn** [comment]
Thanks a lot for the reply. You might be right that it has something to do with my subscription (that could explain why I am not able to get all the Abstracts using both the code (without Pybliometrics) and the Pybliometrics. But I am still confused for the rest, where I am able to access some Abstracts with the code but not with the Pybliometrics since network and API stay the same.

**Comment by Michael-E-Rose** [comment]
You said you can access some documents via pybliometrics, and others not.

Do you have examples of both?

**Comment by vishalmhjn** [comment]
Sorry for the late reply and little confusion. I am not able to get Abstracts at all when using Pybliometrics.
