### ISSUE TITLE
Feature request: automatically store cache files in /tmp folders instead of hidden permanent folders

### ISSUE THREAD

**Issue by Yasin-VU** [pybliometrics-dev/pybliometrics#132]
Currently the cache files of the API downloads go to C/Users/Me/.scopus where they will live on forever and take up a lot of disk space on the C-disk. For the inexperienced user, this means his C disk will slowly fill up and windows cleaning will not help. My request is to add a feature (perhaps as default) to store the cache at a windows temporary folder such that windows cleaning can clean it and open up space.

**Comment by Michael-E-Rose** [comment]
You can do this yourself already. In the folder you mention there's a file `config.ini`. It stores the key but also the paths where pybliometrics should cache files. You can put anything in there, even non-existing folders.

I'm gonna update the [configuration part](https://pybliometrics.readthedocs.io/en/latest/configuration.html) of the documentation.

**Comment by Yasin-VU** [comment]
Thanks for the quick reply and solution!
