### ISSUE TITLE
How to include Authtoken to script

### ISSUE THREAD

**Issue by jyauyong** [pybliometrics-dev/pybliometrics#133]
Hi, I am new to programming and is currently trying out Pybliometrics to retrieve data from Scopus using API. When I first ran my script using my APIkey, there has been a prompt for additional security which I ignored. I got the 401error and was told by Scopus that I will require an Authtoken to access. I try adding the Authtoken to the cache script but it doesn't work. As I am such a novice, I would like to ask how I could include my Authtoken to the script for the it to work? Currently, I am trying out the script as provided in the paper.

**Comment by Michael-E-Rose** [comment]
Hi @jyauyong ! Could you please post the `config.ini` here, in an anoymised form?

**Comment by jyauyong** [comment]
Hi Michael, My apologies. As I am do programming on an ad-hoc basis, I haven't had time to get back to resolving the issue (doesn't help that I am from a biological background). I couldn't quite figure out your question, but i have since uninstall and install pybliometrics and could include the authtoken at the start. Thank you for your prompt response! Stay safe. Regards, Jane-------- Original message --------From: "Michael E. Rose" <notifications@github.com>Date: Sat, 21 Mar 2020, 16:00To: pybliometrics-dev/pybliometrics <pybliometrics@noreply.github.com>Cc: jyauyong <jyauyong@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [pybliometrics-dev/pybliometrics] How to include Authtoken to script (#133)
Closed #133.
