### ISSUE TITLE
api-key cycling fails if succeeding key is also used up

### ISSUE THREAD

**Issue by Yasin-VU** [pybliometrics-dev/pybliometrics#134]
The code on the pybliometrics webpage with tips also mentions a way to change API keys when they are used up, but it has a flaw where it only changes keys once at an error and afterwards just errors out. This is suboptimal, because if your restart your process, your static key list will start with the used up api keys anyway and thus error out if 2 api keys were used up. I suggest a while-loop to cycle through the keys as long as errors continue.

I just wanted to share this for the other users.

PS: Minimum Working example
```
try:
    result = ScopusSearch(my_query)
except Scopus429Error:
    still_error = True
    while still_error:
        config["Authentication"]["APIKey"] = SCOPUS_KEYS.pop()
        try:
            res = ScopusSearch(my_query)
            still_error = False
        except:
            print('error, key pop will happen at top of while top')
```

**Comment by Michael-E-Rose** [comment]
Hi Yasin, thanks for the code! I have not encountered this problem, but I cannot rule out that it would happen with my attempt.

Would it not be possible to encircle everything in a while-loop, and have the try-except-clause within the while loop? Also, would be be interested turning this into a PR? This would give you full credit.
