### ISSUE TITLE
Setting up proxy

### ISSUE THREAD

**Issue by jsk1360** [pybliometrics-dev/pybliometrics#137]
Hi,
This is a bit off-topic. My university provides HTTP VPN, which I can use by entering my univresity credentials. Is there any way to set up SOCKS5 proxy (on Mac OS), so that it provides the addresses that are to be used in the config.ini?
Thanks

**Comment by Michael-E-Rose** [comment]
Hi @jsk1360 , have you seen https://pybliometrics.readthedocs.io/en/stable/configuration.html? The lower part was suggested by someone else, who, I believe, had a very similar problem in #89 .

**Comment by jsk1360** [comment]
Yes, I've seen it. It is the actions prior to that part that is focus of my question, which is basically turning a HTTP proxy to Socks on a Mac. I'll try to figure it out. Thanks!

**Comment by Michael-E-Rose** [comment]
No, sorry, I don't know anything about this.
But if you wanna share what you found out, it'll probably be helpful to future pybliometrics users.
