### ISSUE TITLE
Exception thrown in the example

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#138]
I have tried to run the example provided in the homepage

```
# Document-specific information
from pybliometrics.scopus import AbstractRetrieval
ab = AbstractRetrieval("10.1016/j.softx.2019.100263")
print(ab.title)
print(ab.publicationName)
print(ab.authors)
# Author-specific information
from pybliometrics.scopus import AuthorRetrieval
au2 = AuthorRetrieval(ab.authors[1].auid)
print(au2.h_index)
au1 = AuthorRetrieval(ab.authors[0].auid)
print(au1.affiliation_current)
# Affiliation information
from pybliometrics.scopus import ContentAffiliationRetrieval
aff1 = ContentAffiliationRetrieval(au1.affiliation_current)
print(aff1.affiliation_name)
```

But it throws an exception

> pybliometrics: Scriptable bibliometrics using a Python interface to Scopus
> SoftwareX
> [Author(auid='57209617104', indexed_name='Rose M.E.', surname='Rose', given_name='Michael E.', affiliation=['60105007']), Author(auid='7004212771', indexed_name='Kitchin J.R.', surname='Kitchin', given_name='John R.', affiliation=['60027950'])]
> 32
> [Affiliation(id='60105007', parent=None, type='parent', relationship='author', afdispname=None, preferred_name='Max Planck Institute for Innovation and Competition', parent_preferred_name=None, country_code='deu', country='Germany', address_part='Marstallplatz 1', city='Munich', state='Bayern', postal_code='80539', org_domain='ip.mpg.de', org_URL='https://www.ip.mpg.de/en.html')]
> Traceback (most recent call last):
>   File "main.py", line 15, in <module>
>     aff1 = ContentAffiliationRetrieval(au1.affiliation_current)
>   File "C:\InstalledPrograms\Anaconda3\lib\site-packages\pybliometrics\scopus\affiliation_retrieval.py", line 136, in __init__
>     aff_id = str(int(str(aff_id).split('-')[-1]))
> ValueError: invalid literal for int() with base 10: "[Affiliation(id='60105007', parent=None, type='parent', relationship='author', afdispname=None, preferred_name='Max Planck Institute for Innovation and Competition', parent_preferred_name=None, count

It looks like `ContentAffiliationRetrieval` expects an int, but `AuthorRetrieval.affiliation_current` returns a list instead

Replacing

`aff1 = ContentAffiliationRetrieval(au1.affiliation_current)`

with

`aff1 = ContentAffiliationRetrieval(au1.affiliation_current[0].id)`

make the example work again

**Comment by Michael-E-Rose** [comment]
Thanks @raffaem ! I forgot to update this example with the last release, which changed the `affiliation_current` property of the `ContentAffiliationRetrieval()` class.
