### ISSUE TITLE
Affiliation present in SCOPUS but missing when I retrieve it

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#139]
I'm talking about article with EID "2-s2.0-84858814829".

When I search for it on SCOPUS, it shows the affiliation of the author as "Blekingevägen 5, 757 58 Uppsala, Sweden"

But when I search for it through pybliometrics, using the following code

```
from pybliometrics.scopus import AbstractRetrieval
ab = AbstractRetrieval("2-s2.0-84858814829")
for author in ab.authors:
    print(author)
```

The affiliation equals None. Why is that and how can I solve it?

**Comment by Michael-E-Rose** [comment]
For me it shows `Author(auid='55135905000', indexed_name='Getsadze R.', surname='Getsadze', given_name='Rostom', affiliation=None)`.

The missing affiliation reflects the state of the database. In this case Scopus doesn't know what the affiliation is (after all, it's just a street address) and doesn't combine it with the author either. The document is lacking a lot of information, t.b.h. The DOI is missing, and the references aren't all correct either.

Although examples like these are rare, I found that Scopus does have troubles with math-related text and non-English texts as well.

You can request a document correction [here](https://service.elsevier.com/app/contact/supporthub/scopuscontent/). If the accept the change, it'll take about four week for it to reflect in the database.

**Comment by raffaem** [comment]
Thank you very much for your prompt response!

> In this case Scopus doesn't know what the affiliation is (after all, it's just a street address)

Exactly, if you search the document on SCOPUS, it shows "Blekingevägen 5, 757 58 Uppsala, Sweden".

I am interested in the country only, so for the street address, there is a "Sweden" afterwards and that would enough for me.

I would have expected pybliometrics to return at least that street address (even without the university name)? But I guess this is a problem of SCOPUS and not of the library?

I'm not sure how SCOPUS "extract" the affiliations from the paper, if that is what's happening

**Comment by Michael-E-Rose** [comment]
Yes, unfortunately pybliometrics cannot give you that information because the Scopus API doesn't provide it (if you're interested: type `ab._json` to see what Scopus returns).

Sometimes you might get what you're after performing a search:

```
from pybliometrics.scopus import ScopusSearch
q = "EID(2-s2.0-84858814829)"
s = ScopusSearch(q)
print(s.results)
```

but that's not the case here.

If you don't care about year information, you can try the AuthorRetrieval class:

```
from pybliometrics.scopus import AuthorRetrieval
au = AuthorRetrieval(55135905000)
au.affiliation_history
```
