### ISSUE TITLE
Windows10_pybliometrics.2.4.0 - references in AbstractRetrieval does not function

### ISSUE THREAD

**Issue by ronakrathod842** [pybliometrics-dev/pybliometrics#143]
Hi, 
The references attribute for Abstract Retrieval does not function.
```
from pybliometrics.scopus import AbstractRetrieval
from pybliometrics.scopus import CitationOverview
import pybliometrics 
print (pybliometrics.__version__)
ab = AbstractRetrieval("10.1016/0925-5273(91)90099-F")
print (ab.title)
print (ab.citedby_count)
#print (ab.description)
print (ab.url)
ref = ab.references
print(ref)
```

The output appears as 'None' for ref list/tuple.
The same output was returned for two other doi's as well.

Pls help. thanks :)

**Comment by Michael-E-Rose** [comment]
Hi @ronakrathod842 ! You need to instate the class either in REF or FULL view. See also the documentation for the `.references` attribute: "Requires either the FULL view or REF view."
