### ISSUE TITLE
AuthorRetrieval: [Scopus400Error: Exceeds the maximum number allowed for the service level]

### ISSUE THREAD

**Issue by chrisliiii** [pybliometrics-dev/pybliometrics#145]
Hi,

All methods in AuthorRetrieval work fine in my code except `get_coauthors()`.

Always return `pybliometrics.scopus.exception.Scopus400Error: Exceeds the maximum number allowed for the service level`. I don't know why this is an invalid input. It would great if you can give me any help. Thanks!

**Comment by Michael-E-Rose** [comment]
Can you please provide the code you've been using? In particular, the author ID?

**Comment by chrisliiii** [comment]
> Can you please provide the code you've been using? In particular, the author ID?

Thanks for replying, this is the code I have been using, it worked a few weeks ago.

`from pybliometrics.scopus import config, AuthorRetrieval`
`author_info = AuthorRetrieval(57183980500)`
`coauthors_raw = author_info.get_coauthors()`

**Comment by Michael-E-Rose** [comment]
Found the bug and fixed it. Either wait for the next release or upgrade using the version on the repo.
