### ISSUE TITLE
provide a value for CONFIG_FILE

### ISSUE THREAD

**Issue by sphinxnh** [pybliometrics-dev/pybliometrics#146]
Problem description: it's not possible to set any other path to the config file
Current situation:  
https://github.com/pybliometrics-dev/pybliometrics/blob/3630bf6c9e27488a82d14b4915f143d4a1445695/pybliometrics/scopus/utils/startup.py#L4

The `CONFIG_FILE` constant is set to static string.

Solution proposal: e.g. crossref-common uses environment variables for config constants - there might be more elegant solutions to this problem.

**Comment by Michael-E-Rose** [comment]
What might be a more elegant solution?

**Comment by sphinxnh** [comment]
as mentioned: one possibility is to define environment variables, e.g.:
```python
import configparser
from os.path import expanduser
from os import environ

if 'CONFIG_FILE' in environ:
        CONFIG_FILE = environ['CONFIG_FILE']
else: 
        CONFIG_FILE = expanduser("~/.scopus/config.ini")
[...]
```

I am not a python expert, but this is what I have seen use other libraries, e.g. [1].


[1]: https://gitlab.com/crossref/crossref_commons_py/-/blob/master/crossref_commons/authorization.py
