### ISSUE TITLE
Using a proxy that requires authentication

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#147]
I am at home right now and SCOPUS works only from the network of my university. In fact if I try to download something, it gives me the following error message:

`pybliometrics.scopus.exception.Scopus401Error: The requestor is not authorized to access the requested view or fields of the resource`

My university has a proxy server that allows to go out on the internet with the IP address of the university. However, the proxy requires authentication (username and password). How can I set up such a proxy?

I have tried setting up the block in config.ini like:

    [Proxy]
    ftp = http://username:password@proxy.thing.it:8080
    http = http://username:password@proxy.thing.it:8080
    https = http://username:password@proxy.thing.it:8080

but it still fails with the following error message:

    requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.elsevier.com', port=443): Max retries exceeded with url: /content/abstract/scopus_id/84983158344?view=META_ABS (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))

**Comment by lorenzofamiglini** [comment]
> I am at home right now and SCOPUS works only from the network of my university. In fact if I try to download something, it gives me the following error message:
> 
> `pybliometrics.scopus.exception.Scopus401Error: The requestor is not authorized to access the requested view or fields of the resource`
> 
> My university has a proxy server that allows to go out on the internet with the IP address of the university. However, the proxy requires authentication (username and password). How can I set up such a proxy?
> 
> I have tried setting up the block in config.ini like:
> 
> ```
> [Proxy]
> ftp = http://username:password@proxy.thing.it:8080
> http = http://username:password@proxy.thing.it:8080
> https = http://username:password@proxy.thing.it:8080
> ```
> 
> but it still fails with the following error message:
> 
> ```
> requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.elsevier.com', port=443): Max retries exceeded with url: /content/abstract/scopus_id/84983158344?view=META_ABS (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))
> ```

I'm facing the same issue. But I'm using socks5 protocol. It worked for 3 months and now it's not.

**Comment by raffaem** [comment]
I belive you need a VPN rather than a proxy

**Comment by lorenzofamiglini** [comment]
The University VPN is not available, but why did it work with the proxy before and not anymore? I can't tell if this is a problem stemming from Pybliometrics or the university's own proxy. I don't have low-level control for facing this issue.

**Comment by Michael-E-Rose** [comment]
If it used to work, but now it's not, it's likely a problem either of Scopus or of your institutional network/setup.

Also, looking back at @raffaem's initial message: Where you finally able to tweak the configuration to your working? Because `http://username:password@proxy.thing.it:8080` for both ftp and https looks odd.

**Comment by lorenzofamiglini** [comment]
You made my day! 
From the Pybliometrics documentation, an example is related to the proxy configuration and to the protocol socks5. So, my situation was: 

[Proxy]
ftp = socks5://username:password@proxy.thing.it:8080
http = socks5://username:password@proxy.thing.it:8080
https = socks5://username:password@proxy.thing.it:8080
See here: https://pybliometrics.readthedocs.io/en/stable/configuration.html under set up --> Proxy

When you run something like AuthorSearch, it seems that the script is stuck, but after 5/10 minutes, it throws me this error: 
SOCKS HTTPSConnectionPool(host='api.elsevier.com', port=443). 

Now, I change my config.ini file as follows: 
ftp = http://username:password@proxy.thing.it:8080
http = socks5://username:password@proxy.thing.it:8080
https = http://username:password@proxy.thing.it:8080

And everything is fine! 

Thank you, Michael
