### ISSUE TITLE
Changing configuration values at runtime

### ISSUE THREAD

**Issue by stefanct** [pybliometrics-dev/pybliometrics#148]
Currently there is no documented way to change configuration values (set in `config.ini`) by external code. As of now, it is easily possible to do so by importing the config variable from `startup.py` which is a `ConfigParser` object from the standard `configparser` package:

```
from pybliometrics.scopus.utils import config

print(config['Proxy']['ftp'])
config['Proxy']['ftp']='socks5://localhost:8080'
print(config['Proxy']['ftp'])
```

I thought it would be nice to have a defined interface to do so that remains stable in the future. A `getconfig()` function or similar that gets documented would suffice already IMHO. I am not planing to add one - this is just food for thought.

**Comment by Michael-E-Rose** [comment]
Hi Stefan! Thanks for your suggestion! You are absolutely right, how users can change the config values should be more understandable. I have recently started to improve the corresponding documentation page, but it's not live yet. Will add more in the future.
