### ISSUE TITLE
Add support for startref and refcount parameters in AbstractRetrieval

### ISSUE THREAD

**Issue by olarcher** [pybliometrics-dev/pybliometrics#154]
According to the official Scopus documentation, the [AbstractRetrieval API](https://dev.elsevier.com/documentation/AbstractRetrievalAPI.wadl) supports two URL parameters named `startref` and `refcount` that allow for pagination through the references result list.
These parameters are required if trying to access the `citedby-count` for all refereces cited by a paper. `citedby-count` is only returned when using the `REF` view, which unfortunately only returns 40 references at a time, thus requiring pagination (see also #81).
Is there any way to pass these additional parameters in the current implementation?

**Comment by Michael-E-Rose** [comment]
I think this is a good suggestion, and shouldn't be too difficult. Alas, I cannot work on this until mid-September. Feel free to come up with a PR!

**Comment by Michael-E-Rose** [comment]
Sorry, it took a bit longer - forgot about this issue.
