### ISSUE TITLE
AUTHORIZATION_ERROR - The requestor is not authorized to access the requested view or fields of the resource

### ISSUE THREAD

**Issue by Young1993** [pybliometrics-dev/pybliometrics#155]
I'm getting this error when connected to my university network through a VPN. But the API response is  `AUTHORIZATION_ERROR` and the code is like that

    from pybliometrics.scopus import AuthorRetrieval
    au = AuthorRetrieval(7004212771)
    print(au)

**Comment by Michael-E-Rose** [comment]
How does your config.ini look like? (Please replace the keys by XXX to not show them publicly.)

**Comment by Young1993** [comment]
> How does your config.ini look like? (Please replace the keys by XXX to not show them publicly.)

OK, This is the result when I run the command >  cat /Users/XXX/.scopus/config.ini, could you please check whether the configuration is incorrect. Thanks!
[Directories]
AbstractRetrieval = /Users/XXX/.scopus/abstract_retrieval
AffiliationSearch = /Users/XXX/.scopus/affiliation_search
AuthorRetrieval = /Users/XXX/.scopus/author_retrieval
AuthorSearch = /Users/XXX/.scopus/author_search
CitationOverview = /Users/XXX/.scopus/citation_overview
ContentAffiliationRetrieval = /Users/XXX/.scopus/affiliation_retrieval
ScopusSearch = /Users/XXX/.scopus/scopus_search
SerialSearch = /Users/XXX/.scopus/serial_search
SerialTitle = /Users/XXX/.scopus/serial_title
PlumXMetrics = /Users/XXX/.scopus/plumx

[Authentication]
APIKey = 20XXXXX

**Comment by Young1993** [comment]
And I cannot access any of the API interfaces

**Comment by Young1993** [comment]
And I cannot access any of the API interfaces via pybliometrics.
But when I run 
```
import requests
url = 'https://api.elsevier.com/content/search/scopus?query=KEY%20(covid)+OR+TITLE%20(covid)&apiKey=' + keys[0]
res = requests.request('GET', url)
print(res.json())
```

the response is 

{"search-results":{"opensearch:totalResults":"34158","opensearch:startIndex":"0","opensearch:itemsPerPage":"25","opensearch:Query":{"@role": "request", "@searchTerms": "KEY (covid) OR TITLE (covid)", "@startPage": "0"},"link": [{"@_fa": "true", "@ref": "self", "@href": 
...

**Comment by Michael-E-Rose** [comment]
I've been thinking a couple of days about your problem but I cannot get my head around it. Obviously the key works, but just not though pybliometrics. But I wish to help.

Can you please try to run an ordinary ScopusSearch query with `subscriber=True`?

**Comment by anftorresme** [comment]
I just noticed that my university access to Scopus services through something called "ezproxy", that sets the link to access searching with my institutional ID/Pass. ¿How can I configure pybliometrics to establish the connection to Scopus through my university ezproxy? Just like I do via web explorer.

![Annotation 2020-08-27 151033](https://user-images.githubusercontent.com/31351216/91490376-f5c06380-e877-11ea-92b0-0a5acb1751db.png)
![Screenshot_2020-08-27](https://user-images.githubusercontent.com/31351216/91490378-f658fa00-e877-11ea-97b5-b4b17f7d110a.png)

**Comment by Michael-E-Rose** [comment]
It's the first time I see something like this. Try to add a proxy section in the config.ini, as in https://pybliometrics.readthedocs.io/en/stable/configuration.html

**Comment by Michael-E-Rose** [comment]
Did this finally work, @anftorresme ?

**Comment by lmcnichols** [comment]
I am also having a similar issue. Using my API key via `requests` as shown above seems to work for me, but when I try running the example snippet from the docs 
```
s = ScopusSearch('FIRSTAUTH ( kitchin  j.r. )')
```
I get a `Scopus401Error: The requestor is not authorized to access the requested view or fields of the resource`

**Comment by lmcnichols** [comment]
Update: Explicitly setting `subscriber=False` worked for me.

**Comment by lmcnichols** [comment]
So my university actually does have a subscription. What ended up working for me was using my university's VPN.

**Comment by Michael-E-Rose** [comment]
Yes, it doesn't work w/o VPN. We describe this necessity in https://pybliometrics.readthedocs.io/en/stable/tips.html#error-messages. I suspect direct access via the browser works because of the embedded authentication, whereby Scopus associates your user profile with an institution that pays for you via historic behavior. But that's just a guess.

The reason that `subscriber=False` works is because you're accessing the free but limited content Scopus provides. Less information and longer download times.

**Comment by anftorresme** [comment]
Hi Michael, thank you for helping me. I'm actually have the same trouble that @lmcnichols, but, in my case, i cannot connect through my University VPN so I have the same inquietude.

**Comment by Michael-E-Rose** [comment]
I received word from the Scopus team:
- VPN causes issues with the IP authentication system
- To avoid such problems, request an InstToken through integrationsupport@elsevier.com (state your home institution)
- Add the InstToken to your `config.ini` as described [here](https://pybliometrics.readthedocs.io/en/stable/configuration.html#set-up)

**Comment by ETHLOB** [comment]
Hi Mike, I just received a Token from the Elsevier team and put it in the configuration file as indicated, but I keep getting the 401 error from the API, and it's super strange because I tested these same credentials directly in the dev.elsevier APIs (those whose results look super ugly), and are working there. What do you think happens? By the way! When I do the searches and specify `Subscriber = False`, it does work, but with a token, that wouldn't be my case anymore.

**Comment by Michael-E-Rose** [comment]
How does your config.ini look like?

**Comment by ETHLOB** [comment]
Hi, It looks like this:
![Screenshot 2020-10-10 120917](https://user-images.githubusercontent.com/31351216/95661100-34da0980-0af2-11eb-9ac7-605290ab9f08.png)
Am I doing it right or is there any issue?

**Comment by Michael-E-Rose** [comment]
This looks correct to me, but there might be a bug. To verify, would you please try without the Authentication block, @ETHLOB ? Simply out-commenting with # with do. I suspect pybliometrics continues to use the normal APIKeys.

**Comment by yurimarca** [comment]
I am having the same issues reported previously by @Young1993.
Could you manage to solve this?

Where do we need to set `Subscriber = False`?

**Comment by digitaldust** [comment]
> This looks correct to me, but there might be a bug. To verify, would you please try without the Authentication block, @ETHLOB ? Simply out-commenting with # with do. I suspect pybliometrics continues to use the normal APIKeys.

I am in the same situation, just tried your suggestion, and I get: 
    
    NoSectionError: No section: 'Authentication'

I do have an APIKEY and a InstToken. Any advice more than welcome

**Comment by digitaldust** [comment]
I think the problem is simply the format of the config.ini, what is shown above is not right, it should be:

    [Authentication]
    APIKey = MY_APIKEY
    InstToken = MY_INSTTOKEN

with this, it's now working for me

**Comment by Michael-E-Rose** [comment]
You're right! InstToken must be a section in Authentication.

The documentation is wrong. Wanna fix that? No capacities before next week.
