### ISSUE TITLE
How can I access the database through my University network?

### ISSUE THREAD

**Issue by anftorresme** [pybliometrics-dev/pybliometrics#156]
First and foremost, thank you very much for your attention.

I have come to send you a question that was also expressed in this StackOverflow post because it's also my case. I am affiliated with Scopus services through my university's network, and I obtained my API-KEY by entering my university's data at Dev's page. But when I try to use the pybliometrics library, I get the error "Scopus401Error: The requestor is not authorized to access the requested view or fields of the resource". The pybliometrics guide says that I could also configure the network proxy, but it is a bit ambiguous, and also, due to the pandemic, I connect from my particular network and not directly from the university's one (I get into the base from the institution's page).

I share the SO post, in case it would be helpful to solve this: [https://stackoverflow.com/questions/62262233/using-a-proxy-that-requires-authentication-with-pybliometrics](url)

**Comment by Michael-E-Rose** [comment]
This one is related to the previous #155.

Thanks for making me aware of the SO question! I should make more user of it and from now on I'm going to monitor the scopus tag. Let's also try to solve your problem there.
