### ISSUE TITLE
Add possibility to specify and change SCOPUS API KEY from code

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#161]
I am downloading the pubblications of a relatively large amount of authors, and it frequently happens that after half-a-day of download I get a Scopus429Error: quota exceeded.

Therefore I need to obtain a new API key from SCOPUS and replace the old one in the .scopus config file.

But this also implies re-running my script, and checking from the beginning which authors have been downloaded and which were not.

I would be very useful, instead, to be able to put the new SCOPUS API key in the command line when the error is thrown.

Would it be an implementable feature?

**Comment by Michael-E-Rose** [comment]
Are you on pybliometrics >=2.6?

You can put multiple API keys into your `config.ini`, which are then replaced automatically. See https://pybliometrics.readthedocs.io/en/stable/configuration.html#config-ini

Other than that, you can set configuration files at runtime as specified [here](https://pybliometrics.readthedocs.io/en/stable/configuration.html#runtime).

**Comment by raffaem** [comment]
Yes, that is what I needed!

Thank you very much for that!
