### ISSUE TITLE
Author with ";" in their surname "breaks" ScopusSearch

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#165]
This works

```
>>> from pybliometrics.scopus import AbstractRetrieval
>>> ab = AbstractRetrieval("10.1093/carcin/bgs161")
>>> ab.authors[4]
Author(auid='55343225800', indexed_name='Haldosactue;n L.-A.', surname='Haldosactue;n', given_name='Lars Arne', affiliation=['60006681'])
```

But this doesn't:

```
>>> from pybliometrics.scopus import ScopusSearch
>>> s = ScopusSearch("DOI(10.1093/carcin/bgs161)")
>>> s.results[0].author_names.split(";")
['Aydoǧdu, Eylem', 'Katchy, Anne', 'Tsouko, Efrosini', 'Lin, Chin Yo', 'Haldosactue', 'n, Lars Arne', 'Helguero, Luisa', 'Williams, Cecilia']
```

Now let's be clear: it is evident that the Scopus record is broken. The author is actually called "Haldosén" (maybe the accent is causing problems in Scopus).

But pybliometrics uses the same character ";" to concatenate the strings. 

Maybe `ScopusSearch.results` could return a list in `auth_names` instead of a string? Although that would be backward incompatible. Why does it return a string anyway?

Or maybe, in`scopus_search.py` lines 59-62:

```
surnames = _replace_none([d['surname'] for d in authors])
firstnames = _replace_none([d['given-name'] for d in authors])
info["auth_names"] = ";".join([", ".join([t[0], t[1]]) for t in
                                               zip(surnames, firstnames)])
```

We can remove the characters ";" and "," from the strings `surnames` and `firstnames` before joining them, since those characters in these strings are clearly errors.

**Comment by raffaem** [comment]
Fixed by #167

**Comment by Michael-E-Rose** [comment]
I have not seen such an example in my many years of Scopus usage, so it must be _extremely_ rare.  Maybe this is the only profile that ever had a semicolon in its name.
Given that using regular expression is [relatively slow](https://stackoverflow.com/questions/26214328/why-python-regex-is-so-slow) (at least slower than not using regex), my solution here would be simply to report the problem and wait for Scopus to have fixed that, then refresh the cached files. I already did that, so by next week the name is fixed.

**Comment by raffaem** [comment]
Also having the user split the string on ";" and "," is slower than passing a list.

Is Scopus returns a list, I don't understand why pybliometrics join it with ";" and "," instead of passing the liast directly

I just don't understand this design choice 👍

**Comment by Michael-E-Rose** [comment]
There are two reasons for that
1. That's how a download from Scopus.com looks like. Especially in the beginning it was pybliometrics' design principle, to mimick Scopus behavior as much as possible.
2. Related to that, when putting the results into a pandas DataFrame, and then saving the file, a list (or set) structure makes things worse. For example, upon reading in again, only an `eval()` call could restore the original structure.

In fact, I often split the author ID string myself as well (not always, sometimes I just download and save the author IDs), so I myself could probably save a line of code here and there. But changing the datatype would be a rather big change, so I'm much in favor of keeping it like that.
Sadly, it's difficult to judge how users actually use pybliometrics.
