### ISSUE TITLE
ScopusSearch will not accept a count keyword argument.

### ISSUE THREAD

**Issue by lmcnichols** [pybliometrics-dev/pybliometrics#172]
**Bug report?**

`ScopusSearch` will not accept the `kwd` argument `count`. This is due to the fact its `__init__` function specifies a `count` parameter before it calls its parent `__init__` method, so if the `count` parameter is added as a `kwd`, we get the following error:

`TypeError: __init__() got multiple values for keyword argument 'count'`

**Comment by Michael-E-Rose** [comment]
Thanks for doing that!  Issues are very much appreciated, and PRs even more.

**Comment by lmcnichols** [comment]
My pleasure!
