### ISSUE TITLE
Supress warning

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#174]
I get the following warning with pybliometrics

> C:\Users\Raffaele\anaconda3\lib\site-packages\pybliometrics\scopus\author_retrieval.py:117: UserWarning: Profile with ID 57190510575 has been merged and the new ID is 26026026000.  Please update your records manually.  Files have been cached with the old ID.
>   warn(text, UserWarning)

How can I suppress it?

It interferes with tqdm progress bar

Best

**Comment by Michael-E-Rose** [comment]
This warning inform you, that one of your author IDs is outdated: It doesn't exist any more, but it forwards to the new profile.

If this happens in my code, I typically go back to the data from where this outdated author ID comes from, and I refresh that data.

To suppress these warnings entirely, use `warnings. filterwarnings()` as described [here](https://docs.python.org/3/library/warnings.html).
