### ISSUE TITLE
OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

### ISSUE THREAD

**Issue by interdonatos** [pybliometrics-dev/pybliometrics#175]
Hi, 

I am using pybliometric 2.7 on Python 3.6 for collecting data on the Scopus database. 

I am using it since several months and it always worked fine. Now I get this error on a specific search: 

OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

and I can't understand the reason. The query I am running is a TITLE-ABS-KEY with an OR of several keywords. I wonder if that may have something to do with the number of returned results. 

For instance, the same keywords work fine with the TITLE search, which returns 876 results.

Best regards,
Roberto

**Comment by Michael-E-Rose** [comment]
This is an interesting error message. Can you please write the entire query/code you're using? I'd like to replicate it.

**Comment by interdonatos** [comment]
Sure, here it is :

TITLE-ABS-KEY(plastic OR {single-use plastic} OR {disposable plastic} OR {single-use plastic product} OR {disposable plastic product} OR {plastic product} OR {plastic container} OR {plastic waste} OR {plastic packaging} OR {cosmetics packaging} OR {food packaging} OR {plastic wrapping} OR {plastic wrap} OR {packaging waste} OR {plastic bag} OR {plastic carrier bag} OR {single-use plastic foodware} OR {plastic utensil} OR {single-use plastic stirrer} OR {disposable plastic stirrer} OR {single-use plastic fork} OR {disposable plastic fork} OR {single-use plastic knife} OR {disposable plastic knife} OR {single-use plastic spoon} OR {disposable plastic spoon} OR {plastic food container} OR {plastic beverage container} OR {single-use plastic plate} OR {disposable plastic plate} OR {single-use plastic bowl} OR {disposable plastic bowl} OR {single-use plastic cup} OR {disposable plastic cup} OR {single-use plastic toothpick} OR {disposable plastic toothpick} OR {single-use plastic straw} OR {disposable plastic straw} OR {take-away container} OR {take-away plastic cup} OR {take-away coffee cup} OR {take-away beverage cup} OR {condiment sachet} OR {condiment packet} OR {sanitary product} OR diaper OR nappy OR {sanitary pad} OR {single-use wipe} OR {hygiene product} OR tampon OR {menstrual item} OR {menstrual product} OR {primary microplastic} OR {intentional microplastic} OR {intentionally-added microbead} OR {Expanded PolyStyrene} OR {Expanded polystyrene} OR EPS OR foam OR {foam packaging} OR {packaging foam} OR Styrofoam OR {packing peanuts} OR q-tip OR {cotton swab} OR {cotton bud} OR {plastic water container} OR {plastic bottle} OR {water bottle} OR {beverage bottle} OR {water sachet} OR {sachet drinking water} OR PPE OR {single-use mask} OR {disposable mask} OR {single-use gloves} OR {disposable gloves} OR {single-use PPE} OR {disposable PPE} OR {single-use goggles} OR {disposable googles} OR {personal protective equipment}) AND TITLE-ABS-KEY(legislation OR law OR regulation OR ordinance OR guideline OR ban OR prohibition OR tax OR levy OR levies OR {voluntary reduction} OR {voluntary commitment} OR {voluntary pledge} OR {voluntary action} OR {voluntary initiative} OR {voluntary agreement} OR {public-private partnership} OR {fiscal incentive} OR {tax incentive} OR {fiscal disincentive} OR {tax disincentive})

**Comment by Michael-E-Rose** [comment]
So far I have not been able to replicate the error message due to constant connection time outs. But your query is a very long one, with 2,346 characters. Me and my colleagues repeatedly encountered issues with long queries, so that we finally decided to cut queries at 2,000 characters. So your case is unlikely to be related to the number of results, but instead it's related to the number of characters in your query. My only guidance here is to break it up if possible.

**Comment by interdonatos** [comment]
I will try to reduce the number of characters, but that's weird since the same query works perfectly with the TITLE search, which has more less the same number of characters, i.e. : 

TITLE(plastic OR {single-use plastic} OR {disposable plastic} OR {single-use plastic product} OR {disposable plastic product} OR {plastic product} OR {plastic container} OR {plastic waste} OR {plastic packaging} OR {cosmetics packaging} OR {food packaging} OR {plastic wrapping} OR {plastic wrap} OR {packaging waste} OR {plastic bag} OR {plastic carrier bag} OR {single-use plastic foodware} OR {plastic utensil} OR {single-use plastic stirrer} OR {disposable plastic stirrer} OR {single-use plastic fork} OR {disposable plastic fork} OR {single-use plastic knife} OR {disposable plastic knife} OR {single-use plastic spoon} OR {disposable plastic spoon} OR {plastic food container} OR {plastic beverage container} OR {single-use plastic plate} OR {disposable plastic plate} OR {single-use plastic bowl} OR {disposable plastic bowl} OR {single-use plastic cup} OR {disposable plastic cup} OR {single-use plastic toothpick} OR {disposable plastic toothpick} OR {single-use plastic straw} OR {disposable plastic straw} OR {take-away container} OR {take-away plastic cup} OR {take-away coffee cup} OR {take-away beverage cup} OR {condiment sachet} OR {condiment packet} OR {sanitary product} OR diaper OR nappy OR {sanitary pad} OR {single-use wipe} OR {hygiene product} OR tampon OR {menstrual item} OR {menstrual product} OR {primary microplastic} OR {intentional microplastic} OR {intentionally-added microbead} OR {Expanded PolyStyrene} OR {Expanded polystyrene} OR EPS OR foam OR {foam packaging} OR {packaging foam} OR Styrofoam OR {packing peanuts} OR q-tip OR {cotton swab} OR {cotton bud} OR {plastic water container} OR {plastic bottle} OR {water bottle} OR {beverage bottle} OR {water sachet} OR {sachet drinking water} OR PPE OR {single-use mask} OR {disposable mask} OR {single-use gloves} OR {disposable gloves} OR {single-use PPE} OR {disposable PPE} OR {single-use goggles} OR {disposable googles} OR {personal protective equipment}) AND TITLE(legislation OR law OR regulation OR ordinance OR guideline OR ban OR prohibition OR tax OR levy OR levies OR {voluntary reduction} OR {voluntary commitment} OR {voluntary pledge} OR {voluntary action} OR {voluntary initiative} OR {voluntary agreement} OR {public-private partnership} OR {fiscal incentive} OR {tax incentive} OR {fiscal disincentive} OR {tax disincentive})

**Comment by interdonatos** [comment]
Also, I reduced the length of the query (in fact there was a lot of redundance in the first list), but I still have the same error : 

TITLE-ABS-KEY(plastic OR {cosmetics packaging} OR {food packaging} OR {packaging waste} OR {take-away container} OR {take-away coffee cup} OR {take-away beverage cup} OR {condiment sachet} OR {condiment packet} OR {sanitary product} OR diaper OR nappy OR {sanitary pad} OR {single-use wipe} OR {hygiene product} OR tampon OR {menstrual item} OR {menstrual product} OR {primary microplastic} OR {intentional microplastic} OR {intentionally-added microbead} OR {Expanded PolyStyrene} OR {Expanded polystyrene} OR EPS OR foam OR {foam packaging} OR {packaging foam} OR Styrofoam OR {packing peanuts} OR q-tip OR {cotton swab} OR {cotton bud} OR {water bottle} OR {beverage bottle} OR {water sachet} OR {sachet drinking water} OR PPE OR {single-use mask} OR {disposable mask} OR {single-use gloves} OR {disposable gloves} OR {single-use PPE} OR {disposable PPE} OR {single-use goggles} OR {disposable googles} OR {personal protective equipment}) AND TITLE-ABS-KEY(legislation OR law OR regulation OR ordinance OR guideline OR ban OR prohibition OR tax OR levy OR levies OR {voluntary reduction} OR {voluntary commitment} OR {voluntary pledge} OR {voluntary action} OR {voluntary initiative} OR {voluntary agreement} OR {public-private partnership} OR {fiscal incentive} OR {tax incentive} OR {fiscal disincentive} OR {tax disincentive})

**Comment by interdonatos** [comment]
Update : I ran the query on another machine, and it worked. 

So I guess that the problem was, for some reason, in the vpn : if I run it from my notebook under a vpn (being in smartworking I need my academic vpn to access scopus), it crashes, if I run it on a remote server located at my institute it works...

**Comment by Michael-E-Rose** [comment]
Well, that's interesting to know.

I was about to speculate that it might the error is related to the usage of "TITLE-ABS-KEY". I read some recently in this regard but I couldn't find it again.
