### ISSUE TITLE
Documentation get_document_eids() example is misleading

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#176]
In [documentation examples for AuthorRetrieval class](https://pybliometrics.readthedocs.io/en/stable/examples/AuthorRetrieval.html#) there is written that you could do

`eids = pd.DataFrame(au.get_document_eids(refresh=False))`

and obtain a DataFrame of all the informations for all the author's publications. 

But `get_document_eids()` return only the E-IDs of the publications and nothing else.

To obtain all the informations you have to call `get_documents()`

**Comment by Michael-E-Rose** [comment]
Good catch, thank you! I'm gonna fix that soon.
