### ISSUE TITLE
Missing time line of affiliation history

### ISSUE THREAD

**Issue by pierrehenry14** [pybliometrics-dev/pybliometrics#177]
AuthorRetrieval() does not provide the time line of the author's affiliation history, which is available on Scopus's author profile. 

For example, `AuthorRetrieval('57204465067').affiliation_history` returns the followings,

`[Affiliation(id='60011048', parent=None, type='parent', relationship='author', afdispname=None, preferred_name='IBM Research', parent_preferred_name=None, country_code='usa', country='United States', address_part='1101 Kitchawan Road', city='Yorktown Heights', state='NY', postal_code='10598', org_domain='research.ibm.com', org_URL='http://www.research.ibm.com/')]`

The affiliation history on this author's webpage shows the followings,
`2018 - 2020 | IBM Research, Yorktown Heights, United States`

Is it possible to add `2018-2020` as an additional item to the `affiliation_history` results?

**Comment by Michael-E-Rose** [comment]
The reason for that is that, unfortunately, Scopus does not provide this information via the API.

You can verify yourself. The entire query result that pybliometrics parses for you is available through property `._json`. The lower half contains the key `'affiliation-history'`.

**Comment by Michael-E-Rose** [comment]
Having said that, what I do to reconstruct someone's affiliation history is to parse all associated documents with `ScopusSearch()` class. You cycle through all the publications, find the ID of your author in the string of author IDs, store its index, and pick the corresponding affiliation ID in the string of affiliation IDs.
