### ISSUE TITLE
`_write_json` fails if data is a bytes instance

### ISSUE THREAD

**Issue by quaquel** [pybliometrics-dev/pybliometrics#178]
**Bug report?**
I am playing around with pybliometrics and sosia and I am running into what seems to be a bug. 

I am on a Mac, anaconda distribution with python 3.8.5 and pybliometrics '2.7.1'. 

The issue  is with `_write_json` which fails if data is `b''`. A format string like `text = f"{dumps(data, separators=(',', ':'))}\n"
` fails if data is a bytes string. I have for now monkeypatched it by first decoding data if it is an instance of bytes.

The fact that data is `b''` is due to 

```Python
                if download:
                    data = "".encode('utf-8')
```

in the `__init__`

**Comment by Michael-E-Rose** [comment]
Thanks for this bug report! What kind of query did you run? Was this a query without results?

**Comment by quaquel** [comment]
I am using pybliometrics via sosia, so reconstructing the exact query is a bit tricky. 

Based on stepping through the code with a debugger, it seem the query is for an author ID + publication year. 

The response (i.e. the `res` dict) has  `opensearch:totalResults:0`. Further down, I see `'error': 'Result set was empty'`. Moreover, `n` is also 0. Together, this indeed suggests that the query had no results.

**Comment by Michael-E-Rose** [comment]
Yes indeed, this was related to empty results being dumped. Should be a rare event, so thanks for finding this!
