### ISSUE TITLE
Retrieve old SJR and SNIP lists not only the most recent values

### ISSUE THREAD

**Issue by mmagaldi77** [pybliometrics-dev/pybliometrics#179]
From the Elsevier Scopus Interactive API pages it looks like the [Serial Title API](https://dev.elsevier.com/scopus.html#!/Serial_Title/SerialTitleSearch) allows for a `date` parameter to specify a year or range of years for which to return yearly metric data. Example: `date=2014-2016`

The serial metadata response seems to be correct

 Will it be possible to use this feature in the [Serial Title class](https://pybliometrics.readthedocs.io/en/stable/reference/pybliometrics.SerialTitle.html) ?

Thanks in advance!

**Comment by Michael-E-Rose** [comment]
I did not know that - great find! And yes, it should be available.

Want to give it a try? No capacities before next weekend.

**Comment by mmagaldi77** [comment]
Great, I will give a try and most likely you will correct

**Comment by mmagaldi77** [comment]
@Michael-E-Rose pull request submitted. I had some issues with removing a duplicated line for the current metric year but, hopefully, is good enough

**Comment by Michael-E-Rose** [comment]
Hi @mmagaldi77 , did you get my review request in PR #180 ? I left some comments there. I'm waiting for that PR to finish before the next release, but I am aiming for beginning of next week, if not earlier.

**Comment by mmagaldi77** [comment]
Yes sorry @Michael-E-Rose I will work on it during this weekend or hopefully sooner. Will that work for you?

**Comment by Michael-E-Rose** [comment]
That's totally! I appreciate any contribution in PRs, so no pressure. Just wanted to make sure you get the review.
