### ISSUE TITLE
option to exclude self-cites from Citation Overview yearly citation counts

### ISSUE THREAD

**Issue by IvanSterligov** [pybliometrics-dev/pybliometrics#184]
Hello and thanks for a great tool which I use a lot! 

I propose you implement a papameter for Citation Overview query to filter out self-citations. It should be simple, because it is already implemented in the API itself:

https://dev.elsevier.com/documentation/AbstractCitationAPI.wadl see param 'citations' option 'exclude-self'

This would greatly help those studying intersection of government bibliometric evaluations and citation behaviour, among others. 

Best regards,
Ivan Sterligov
https://scholar.google.com/citations?user=HApth4AAAAAJ&hl=en

**Comment by Michael-E-Rose** [comment]
Hi Ivan! This was already implemented in PR #182, and it's life since [pybliometrics 2.9](https://pybliometrics.readthedocs.io/en/stable/changelog.html#id2).

**Comment by IvanSterligov** [comment]
Great news! sorry for missing this info while reading the reference

**Comment by Michael-E-Rose** [comment]
No problem! If you're on twitter, follow the hashtag [#pybliometrics](https://twitter.com/hashtag/pybliometrics?f=live) to stay up-to-date.
