### ISSUE TITLE
AbstractRetrieval.correspondence fails with AttributeError

### ISSUE THREAD

**Issue by herreio** [pybliometrics-dev/pybliometrics#185]
**Bug report?**

Hi! I tried to access the `correspondence` property of an `AbstractRetrieval` object and ran into an unhandled `AttributeError`:

```python
from pybliometrics.scopus import AbstractRetrieval
absdoc = AbstractRetrieval("2-s2.0-85100260389", view="FULL", id_type="eid")
absdoc.correspondence
```

```txt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/pybliometrics/scopus/abstract_retrieval.py", line 225, in correspondence
    aff = corr.get('affiliation', {})
AttributeError: 'list' object has no attribute 'get'
```

The `correspondence` routine only considers a single correspondence author, but there are cases (as the one above) with several! They are parsed as a `list` rather than a `dict`, so the `corr.get('affiliation', {})` in [line 225](https://github.com/pybliometrics-dev/pybliometrics/blob/0e988a051ad0fd58bd6c6e2dda94aaf70fc84359/pybliometrics/scopus/abstract_retrieval.py#L225) fails.

Pybliometrics: 2.9.1
Python: 3.6.12

**Comment by Michael-E-Rose** [comment]
Fixed in #186
