### ISSUE TITLE
429 Error with too frequent download

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#191]
Repeated AuthorSearch quickly returns error 429 (quota exceeded).

In order to avoid it, you need a delay between consecutive calls.

This is a behavior that IMHO should be documented.

**Comment by Michael-E-Rose** [comment]
They delay would take 1 week - I don't think anybody would let their script running for that long.

There's some information on keys here: https://pybliometrics.readthedocs.io/en/stable/configuration.html#config-ini:
> ...refer to your API Keys, of which you can register 10 for your Scopus account. If you provide all of them (separated by a comma), pybliometrics automatically replaces a depleted key with a random one of the others. 

What more would you want?

**Comment by raffaem** [comment]
I had ~330 authors and it took 15 minutes or so with the delay, not 1 week

Do you mean that, if I put more than one API key, another one is used when it throws 429, and after all API keys have been exhausted it will re-start from the beginning but in the meantime the first one have been "repleted"?

Is that how it works?

**Comment by Michael-E-Rose** [comment]
Yes, very close! pybliometrics cycles through "free" keys for you until all of them are depleted.

But then it stops and throughs the 429. Scopus resets used keys 1 week after they've first been used. But since pybliometrics doesn't log when you start, it doesn't know when keys get reset.

**Comment by raffaem** [comment]
> Scopus resets used keys 1 week after they've first been used.

I used the same API key that threw the 429 over and over. Inside the same hour.

Just that restarting with the 10 second delay it doesn't throw the error anymore.

What I mean: I didn't change the API key after the 429 error.

**Comment by Michael-E-Rose** [comment]
That's unusual. Are you positive you might not accidentally have another API key in your config.ini? Scopus describes the quota reset procedure here: https://dev.elsevier.com/api_key_settings.html

**Comment by raffaem** [comment]
Yes I have one API key in `config.ini`.

I never changed it since the start of the procedure.

Just run first 8 authors, throw 429, re-run, re-throw 429, put 10 second delay, re-run, and it downloaded all of them (~330 authors)

I now understand why you said it would require one week. There was an information asymmetry between us!

**Comment by Michael-E-Rose** [comment]
That is a very interesting behavior! I would expect delays to help with 501 errors, since waiting complies with Scopus' throttling which we have not (yet) implemented.

Can you share the author IDs you've been working on? Did this occur before with other things?

**Comment by raffaem** [comment]
Sorry for the delay Michael, I completely forgot this.

Unfortunately I cannot share the list of authors I looked for.

I can share the code I have been using. you can fill in your own list of authors. With 10/15 authors you should obtain 429 Error without the `time.sleep` and no errors with the `time.sleep`

( I know it's a bad habit to modify the dataframe you are looping over, it's just a bit of code written in a hurry)

```
#!/usr/bin/env python
# coding: utf-8

from pybliometrics.scopus import AuthorSearch
import pandas as pd
import time
import json

col = "s.authors"
file = "out.xlsx"
indf = pd.read_excel(file)

for index, row in indf.iterrows():
    
    if col in row and row[col] is not None:
        print("Author already searched")
        continue

    name = row["Name"]
    surname = row["Surname"]
    
    # this returns a list of named tuples
    # see: https://pybliometrics.readthedocs.io/en/stable/examples/AuthorSearch.html
    # s = AuthorSearch('AUTHLAST(Selten) and AUTHFIRST(Reinhard)')
    query = f'AUTHLAST({surname}) AND AUTHFIRST({name})'
    s = AuthorSearch(query, refresh=True)

    print(f"Looking for n. {index} ({name}, {surname}) (query={query})")
	        
    if s is None:
        print(f"\t`s` is None")
        continue      

    if s.authors is None:
        print(f"\t`s.authors` is None")
        continue
    
    #eids = ""
    #for auth in s.authors:
    #    eids += auth.eid+";"
        
    indf.loc[index, col] = json.dumps(s.authors, ensure_ascii=False)
    indf.to_excel(file, index=False)
    
    time.sleep(10)
    
print("Script ended")
```

**Comment by Michael-E-Rose** [comment]
Here's the solution to the puzzle: Of one downloads stuff too quickly, the APIs return the 429 error as well:

"If requests exceed the throttling rate, the APIs also return an http 429 TOO MANY REQUESTS msg." 
https://dev.elsevier.com/api_key_settings.html

By putting your code to sleep, you adhere to the throttling that I have yet to implement. I'm working on it.

**Comment by Michael-E-Rose** [comment]
The 429 error because of too fast downloading should now be a thing of the past.

pybliometrics' throttling is sophisticated: Does not just wait 1 sec between each call, but really takes into account how many calls per second this particular API allows.
