### ISSUE TITLE
About the 401 code, when I call AuthorSearch

### ISSUE THREAD

**Issue by FavorMylikes** [pybliometrics-dev/pybliometrics#193]
I have tried ScopusSearch, checked api key, and that worked fine for me. 

But when I use AuthorSearch, it throw 401 code below

`The error is Scopus401Error: The requestor is not authorized to access the requested view or fields of the resource`

And I have used the native http request like `https://api.elsevier.com/content/search/author?apiKey=**********`, throw the same exception.

What should I do next?

**Comment by Michael-E-Rose** [comment]
Before I can help I need some more answers.
Does any other class, e.g., AuthorRetrieval(), work? Did AuthorSearch() ever work for you? Are you behind an institutional network or are you using InstToken?

**Comment by FavorMylikes** [comment]
@Michael-E-Rose 
After some search, I found a api [list](https://dev.elsevier.com/api_key_settings.html)

Seems I can not get the response if I'm not a subscriber.

|#|API Name|Enabled or Disabled|Non-subscriber|Academic Subscriber|Weekly Quota|Requests/second
|-|-|-|-|-|-|-|
|1|Serial Title|Enabled|STANDARD, COVERIMAGE views / Default 25 results / Max 200 results|STANDARD, COVERIMAGE, ENHANCED Default 25 results / Max 200 results|20,000|6
|2|Citations Count Metadata|Enabled|N/A|STANDARD view / Default 25 results / Max 200 results|50,000|10
|3|Citations Overview|Disabled|N/A|STANDARD view / Default 25 results / Max 200 results|20,000|4
|4|Subject Classifications|Enabled|No restrictions|No restrictions|N/A|N/A
|5|Abstract Retrieval|Enabled|META view|All views, default FULL view|10,000|9
|6|Affiliation Retrieval|Enabled|N/A|All views, default STANDARD view|5,000|9
|7|Author Retrieval|Enabled|N/A|All views, default STANDARD view|5,000|3
|8|Affiliation Search|Enabled|N/A|Default 25 results / Max 200 results 5000 item result limit|5,000|6
|9|Author Search|Enabled|N/A|Default 25 results / Max 200 results 5000 item result limit|5,000|2
|10|Scopus Search|Enabled|STANDARD view / Default 25 results|STANDARD view / Max 200 results COMPLETE view / Max 25 results COMPONENT view / Max 25 results 5000 item total result limit without 'cursor' pagination. See Q4 of FAQ|20,000|9
|11|Author Feedback|Disabled|N/A|N/A|N/A|N/A

**Comment by Michael-E-Rose** [comment]
Yes, that's what I describe on https://pybliometrics.readthedocs.io/en/stable/tips.html#error-messages
