### ISSUE TITLE
ScopusSearch Complete View N authors limit? 

### ISSUE THREAD

**Issue by IvanSterligov** [pybliometrics-dev/pybliometrics#194]
Hello and many thanks for your work, 

I'm using pybliometrics to do fractional counting on large sets of megacollaboration papers (LHC, epidemiology, etc). 

Generally the "au-id to af-id" field of ScopusSearch complete view works well, but in this case there seems to be a limit on total number of authors displayed (max 100 authors), so for papers exceeding this limit I have to use AbstractRetrieval instead.

Is this max100 author limit implemented in pybliometrics or in scopus api itself? I did not find any mentions of it in https://dev.elsevier.com/sc_search_views.html or elsewhere. 

Best regards,
Ivan

**Comment by Michael-E-Rose** [comment]
Hi @IvanSterligov ! Yes indeed, it's a restriction on their side, unfortunately. And yes, it's not documented (some other things aren't). So it's not something pybliometrics does; You can verify yourself by looking at the cached json.

**Comment by IvanSterligov** [comment]
Ah, just as I expected... thanks for clarification!
