### ISSUE TITLE
Max retries exceeded 

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#195]
I get this error after some time when I download publications for a series of authors.

Do you know what might cause it?

```
ConnectionError: HTTPSConnectionPool(host='api.elsevier.com', port=443): Max retries exceeded with url: /content/search/scopus?count=25&view=COMPLETE&query=AU-ID%2855925584600%29&cursor=AoJRlNJMMjItczIuMC04NDkwMDI5MDE3Mg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ec38f28b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by Michael-E-Rose** [comment]
You might be violating Scopus' throttling, although that normally caused other error codes 

I recently implemented throttling. Would you mind installing from GitHub directly and check whether the error persists? `pip install git+https://github.com/pybliometrics-dev/`
