### ISSUE TITLE
ImportError: cannot import name 'KEYS' from 'pybliometrics.scopus.utils.startup' (/usr/local/lib/python3.7/dist-packages/pybliometrics/scopus/utils/startup.py)

### ISSUE THREAD

**Issue by etsern** [pybliometrics-dev/pybliometrics#196]
**Bug report**
I am using pybliometrics in googlecolab. I am using Scopus Api key with tokken. Everything was working fine, but this week the following error appears: `ImportError: cannot import name 'KEYS' from 'pybliometrics.scopus.utils.startup' (/usr/local/lib/python3.7/dist-packages/pybliometrics/scopus/utils/startup.py)`. It appears, when I use ScopusSearch.

How to solve this problem?

```
/usr/local/lib/python3.7/dist-packages/pybliometrics/scopus/utils/get_content.py in get_content(url, api, params, **kwds)
     53     from simplejson import JSONDecodeError
     54 
---> 55     from pybliometrics.scopus.utils.startup import _throttling_params, KEYS
     56 
     57     # Set header, params and proxy

ImportError: cannot import name 'KEYS' from 'pybliometrics.scopus.utils.startup' (/usr/local/lib/python3.7/dist-packages/pybliometrics/scopus/utils/startup.py)
```

**Comment by Michael-E-Rose** [comment]
Which `pybliometrics.__version__` are you using? 3.0.0?

**Comment by etsern** [comment]
pybliometrics-3.0.0

**Comment by Michael-E-Rose** [comment]
And how does your `config.ini` look like? Is it somehow similar to what's described in https://pybliometrics.readthedocs.io/en/stable/configuration.html?

**Comment by trifen** [comment]
I had the same problem. I have solved this problem by removing the "try-except" structure in "startup.py". Specifically, I replace the following code:

-----------------------------------------------------------
try:
    config = configparser.ConfigParser()
    config.optionxform = str
    config.read(CONFIG_FILE)
    # Parse keys with fixture for RTFD.io
    try:
        KEYS = [k.strip() for k in config.get('Authentication', 'APIKey').split(",")]
    except configparser.NoSectionError:
        pass
except FileNotFoundError:
    import warnings
    text = "pybliometrics did not find a configuration file.  Please issue "\
          "pybliometrics.scopus.utils.create_config() to start the process "\
          "which guides you through the generation of the configuration "\
          "file or read https://pybliometrics.readthedocs.io/en/stable/configuration.html."
    warnings.warn(text, UserWarning)
-----------------------------------------------------------

with the code:

-----------------------------------------------------------
config = configparser.ConfigParser()
config.optionxform = str
config.read(CONFIG_FILE)    
KEYS = [k.strip() for k in config.get('Authentication', 'APIKey').split(",")]
-----------------------------------------------------------

**Comment by Michael-E-Rose** [comment]
I remember in 3.0.0 I caused a bug that prevented new users to properly run pybliometrics the first time. It's not occurring anymore, and I think it's because of 71a022d5ba6ebceb6ab271d63cbefff23f1767a0 possibly in conjunction with c05526b3b979abc6bb0a23938c7c1125f0713e3b.

**Comment by fahmij8** [comment]
@Michael-E-Rose Please re-open this issue, it seems like if you try this using python 3.7 or higher this error will occur and it's bugging me.

**Comment by fahmij8** [comment]
I see, yup I do. Thanks for the assistance!

**Comment by Michael-E-Rose** [comment]
The import failure is essentially due to a fixture I implement to automatically generate the documentation. I bet the import on google colab fails for the same reason. I might find time later this week to try another fixture, but in any case, the colab doesn't provide the necessary access rights.
