### ISSUE TITLE
Documentation is wrong on where config.ini is stored

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#201]
The [documentation](https://pybliometrics.readthedocs.io/en/stable/configuration.html) says that:

> pybliometrics stores values it needs for operation in a config file. That file is either in ~/.pybliometrics/config.ini or in ~/.pybliometrics/config.ini

First, I can see no difference between the two directories.

Second, on my system the config file is actually stored in `~/.scopus/config.ini`

**Comment by Michael-E-Rose** [comment]
Thanks for the hint! One should be `.pybliometrics`, the other `.scopus`. Users that started using pybliometrics before 3.0 will have the `.scopus` folder (unless they rename it), all others the `.pybliometrics` folder.
