### ISSUE TITLE
Change documentation of rangeCount

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#207]
The current documentation for CitationOverview.rangeCount [states](https://pybliometrics.readthedocs.io/en/stable/classes/CitationOverview.html)

> Number of citations for the specified years for each document.

I understood it would return a matrix with years in the rows and documents in the columns, or something like that.

I would change it to

>  Number of citations *over the specified year range* for each document.

**Comment by Michael-E-Rose** [comment]
You're right, the documtation could be clearer. What about `Total citation count over the specified year range for each document`?

Wanna put together a PR?
