### ISSUE TITLE
SerialTitle.citescoreyearinfolist throws TypeError

### ISSUE THREAD

**Issue by still-coding** [pybliometrics-dev/pybliometrics#215]
Hello!
I'm getting TypeError exception when trying to get citescoreyearinfolist value from SerialTitle. My code basically looks like this:
```python3
st = SerialTitle('1843-6110')
print(st.citescoreyearinfolist)
```
And traceback:
```
Traceback (most recent call last):
  File "./fill_db.py", line 430, in <module>
    print(st.citescoreyearinfolist)
  File "/home/ivan/anaconda3/lib/python3.8/site-packages/pybliometrics/scopus/serial_title.py", line 27, in citescoreyearinfolist
    tracker = (int(d['citeScoreTrackerYear']),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
Maybe I'm doing something wrong?

Pybliometrics version is 3.1.0.

**Comment by Michael-E-Rose** [comment]
This is a bug affecting sources whose coverage is discontinued. That's why they don't have tracked metrics, which is for the ongoing year. Let me fix this ASAP...

**Comment by still-coding** [comment]
Thank you for quick fix and for this great project!
