### ISSUE TITLE
How to find 5000+ authors using pybliometrics.scopus.AuthorSearch?

### ISSUE THREAD

**Issue by Farbeyonder** [pybliometrics-dev/pybliometrics#218]
1) How to find 5000+ authors using pybliometrics.scopus.AuthorSearch?

When I use **query = f'AF-ID({XID})'** to find all authors in an Affiliation, I get the following error: 
ScopusQueryError: Found 8953 matches. The query fails to return more than 5000 entries. Change your query such that it returns fewer entries.

2) If finding 5000+ authors is not possible, how can I find fewer entries (e.g. around 3000) by section (section 1, 2, 3) so I can piece the 3 sections together for all authors in an Affiliation?

**Comment by Michael-E-Rose** [comment]
This question would have found a better place on StackOverflow.

But here is the answer anyways: You need to make the query more fine-grained within a mutually exclusive loop: `AF-ID(1234567) AND AU-ID(1*)`, where you you replace `1` with `2` in the next run, and so on.
