### ISSUE TITLE
get_key_reset_time returns 1970

### ISSUE THREAD

**Issue by mark-todd** [pybliometrics-dev/pybliometrics#219]
A bug has appeared I think due to a change in scopus' API, as I haven't changed my pybliometrics version. The unix timestamp returned from scopus for reset time used to be something of the form "1638444000" and is now of the form "1638444" , so all reset times are now displayed as being in 1970.
```
res = AuthorSearch("AU-ID(57209617104)")
res.get_key_reset_time()
#'1970-01-20 00:07:24'
```
Pybliometrics version "^3.0.1", but I imagine this would be true for any version.

**Comment by Michael-E-Rose** [comment]
Indeed, their precision must have changed. Thanks for alerting me to this! Unfortunately the Scopus guys do not inform us of changes in the API.
