### ISSUE TITLE
Docs: Missing docstrings for AbstractRetrieval

### ISSUE THREAD

**Issue by astrochun** [pybliometrics-dev/pybliometrics#224]
I think the class' docstring is missing, isn't?

_Originally posted by @Michael-E-Rose in https://github.com/pybliometrics-dev/pybliometrics/issues/222#issuecomment-989563260_

**Comment by Michael-E-Rose** [comment]
Um, why a new issue for this? Should I wait merging PR #222 for another commit of yours?

**Comment by astrochun** [comment]
> Um, why a new issue for this? Should I wait merging PR #222 for another commit of yours?

The purpose of #222 is to add ORCiD information to one of the property. Since the docstrings is entirely missing, this seems more like a separate issue as you're more familiar with `AbstractRetrieval` and your styling for docstrings.

**Comment by Michael-E-Rose** [comment]
I think that's a missunderstanding (see PR #222).

The class' docstring is in in `__init__`.

**Comment by astrochun** [comment]
> I think that's a missunderstanding (see PR #222).
> 
> The class' docstring is in in `__init__`.

I see. Is there a reason why you have it in `__init__` instead of having it associated at the top level with the class? I've often seen the latter, so an immediate search for the docs within my IDE was why I thought it was empty. Also, is there a reason why you have the "dunder" methods at the end? These are usually show in `help` near the top.

**Comment by Michael-E-Rose** [comment]
I think that's a question for @jkitchin  :)
