### ISSUE TITLE
The examples/tutorial

### ISSUE THREAD

**Issue by langongjin** [pybliometrics-dev/pybliometrics#234]
Hi,

I remember that I used pybliometrics with a tutorial where a lot of examples are given. Therefore, I designed the code for my tasks as shown in the pictures. But I can not find the tutorial with the examples anymore. Could you show me that? Thanks a lot!
![Screenshot from 2022-01-09 19-57-42](https://user-images.githubusercontent.com/13703853/148681432-83e416fd-fa34-4cca-9f86-ef36e36c4db4.png)
![Screenshot from 2022-01-09 19-57-23](https://user-images.githubusercontent.com/13703853/148681437-cb64ff1a-cbd7-45db-a286-a62455bc7bb3.png)

**Comment by Michael-E-Rose** [comment]
These are nice graphs but I have not created them. Why don't you ask the authors of the paper? Once you found the tutorial, please let us know where it lives.

**Comment by langongjin** [comment]
I made the figures by following a tutorial two years ago. But I can not find the tutorial anymore. Maybe somebody knows that. Therefore, I proposed this issue. Hope somebody knows the tutorial and let me know.

**Comment by Michael-E-Rose** [comment]
Maybe you can find someone on twitter, under the hastag #pybliometrics . At least some people follow it.
