### ISSUE TITLE
Who put my name in AUTHORS and my changes in ChangeLog?

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#235]
I am trying to push a simple change [here](https://github.com/raffaem/pybliometrics/commit/c05b808407e04badbc3682dbcdb15a9effd15b5d).

However something created an AUTHORS file, ad put my name in it, and a ChangeLog, and put my changes in it.

How did those things ended there?

**Comment by raffaem** [comment]
The `setup.py install` generated them:
```
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.0s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.0s)
```

**Comment by raffaem** [comment]
It's actually [pbr that adds them](https://docs.openstack.org/pbr/3.0.0/):
```
AUTHORS: Generate AUTHORS file from git log
ChangeLog: Generate ChangeLog from git log
```

**Comment by Michael-E-Rose** [comment]
That sounds correct. But there's flags that prevent pbr to generate those two files.

I forgot to mention that the list you've found is the reason for the flags. Intead we maintain both files manually.

**Comment by raffaem** [comment]
> That sounds correct. But there's flags that prevent pbr to generate those two files.

There seems to be environmental variables to skip creation of AUTHORS and ChangeLog, but I have not found a solution to hard code it.

So it looks like I have to either remember to set the environment variables every time I setup, or remember to don't add the files to the commit (so I cannot call `git add -A`) or have a commit with those files added.

> I forgot to mention that the list you've found is the reason for the flags. Intead we maintain both files manually.

I didn't get that. Those files seems not to be present in the main repo.

**Comment by raffaem** [comment]
Can we add AUTHORS and ChangeLog to .gitignore? So they don't get mistakenly added when you git add some modifications for a forked version.

Do you use those environmental variables when you try to `python setup.py install` also?

I find this pbr a bit confusing. Those files are not erased with a `python setup.py clean --all` either.

You should have some way to hard code skipping the generation of those files. Especially since you have your own, you don't want the pbr generated one?

**Comment by Michael-E-Rose** [comment]
Those two files are hard-coded members of every repository, at least AUTHORS. You can put them in your .gitignore, but here there's no point in doing that.

Since I execute above command manually in the console, the questions you ask don't really apply for this repo.

**Comment by raffaem** [comment]
uhm fair enough.

I'll try to remember not to add them when I commit.
