### ISSUE TITLE
Main profile is one of [long list here]

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#240]
I have some output from pybliometrics.

One of such output is:
> Profile with ID 7801319381 has been merged and the new ID is 8619430100.  Please update your records manually.  Files have been cached with the old ID.

I understand that.

Scopus recognized that the author had two profiles (8619430100 and 7801319381), and merged them into 8619430100

Another output is:

> UserWarning: Author profile with ID 7102423551 has been merged and the main profile is now one of 56810507300, 57218944905, 55782805100, 57218944900, 55708578300, 57197921116, 36956741200, 57217694181, 57217694180, 57218945044, 57217694179, 55208024500, 57217694178, 56506475300, 57201605855, 57034398500, 57201605849, 57218944958, 57218944831, 55208024600, 57189007372, 57216866899, 57189007373, 57218944821, 57218944947, 57190984043, 57218944841, 57218944966, 57218944839, 57213953651, 57213953654, 57218944833, 57218944990, 57218944986, 57218944982, 57218944855, 57218945109, 57218944977, 55971582200, 57213953637, 57218944877, 55708578200, 57203074807, 57212673989, 57218944866, 55485949400, 57218944992, 57197921086, 57216136231, 57206213176, 57218945016, 57206213169, 57218945009.  Please update your records manually.  Functionality of this object is reduced.

I don't understand that.

What does it mean that "the main profile is now one of" [LIST OF 53 SCOPUS ID]?

Do I have to pick one of the 53 Scopus IDs?

Do I get to choose?

How do I pick the correct Scopus ID? Randomly?

**Comment by Michael-E-Rose** [comment]
Both cases are the same: Scopus doesn't redirect to the new author ID, but instead returns possible candidates.

I don't know why they do that.

Because when you insert the old ID in a scopzs.com author URL, you get redirected to the new author profile.
