### ISSUE TITLE
TypeError in ScopusSearch

### ISSUE THREAD

**Issue by mattianeroni** [pybliometrics-dev/pybliometrics#247]
Code to reproduce the bug:
ScopusSearch(query="REF(2-s2.0-85108287295)", subscriber=True)

# output
/lib/python3.9/site-packages/pybliometrics/scopus/scopus_search.py in results(self)
     97                       citedby_count=int(item['citedby-count']),
     98                       openaccess=int(item['openaccess']),
---> 99                       freetoread=freetoread[-1]["$"],
    100                       freetoreadLabel=freetoreadLabel[-1]["$"],
    101                       eIssn=item.get('prism:eIssn'),

TypeError: string indices must be integers

**Comment by raffaem** [comment]
You need the git version of pybliometrics

**Comment by Michael-E-Rose** [comment]
Oh yes! Turns out I fixed this in f7023805bce5be49f3a180a5fee6db39ef6123e5
