### ISSUE TITLE
Cannot connect to proxy

### ISSUE THREAD

**Issue by yss-cy** [pybliometrics-dev/pybliometrics#250]
I use the school vpn, add proxy (the IP of the school website) in the config, and execute the following code
```
from pybliometrics.scopus import ScopusSearch
s=ScopusSearch('ISSN(1532-849X) AND PUBYEAR IS 2010')
print(s)
```
But the following error
```
HTTPSConnectionPool(host='api.elsevier.com', port=443): Max retries exceeded with url: /content/search/scopus?count=25&view=COMPLETE&query=ISSN%281532-849X%29+AND+PUBYEAR+IS+2010&cursor=%2A (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
```
How to solve it, looking forward to your answer, thank you

**Comment by Michael-E-Rose** [comment]
This can have different reasons, see https://pybliometrics.readthedocs.io/en/stable/access.html.
1. Does your institution actually provide access to the Scopus API (not just scopus.com)
2. Are all of your proxies correctly set? Most setups are fine with just VPN
3. If none works, try to retrieve an InstToken from the Scopus Integration Support
