### ISSUE TITLE
TypeError: create_config() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by gchlepos** [pybliometrics-dev/pybliometrics#252]
I can't use the prompt to enter the api key so im trying to provide the optional parameter(api_key) to create_config but I get this error: TypeError: create_config() takes 0 positional arguments but 1 was given. Is there any other way to to submit my api_key without using the prompt? Thanks!!

**Comment by Michael-E-Rose** [comment]
Which version of pybliometrics are you using?

**Comment by gchlepos** [comment]
I am using 3.1.0

**Comment by Michael-E-Rose** [comment]
And how do you think is code, that was [introduced in in 3.2.0](https://pybliometrics.readthedocs.io/en/stable/changelog.html#id2) supposed to work for your case?

Lessons learned:
1. Always upgrade your package before thinking about writing an issue
2. Do _not_ remove the template in the issue, which clearly asks you to state the version you are using.
