### ISSUE TITLE
Classification group - invalid literal

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#258]
```python3
from pybliometrics.scopus import AuthorRetrieval
scopus_id = "12792377500"
au = AuthorRetrieval(scopus_id, refresh=True)
print(au.classificationgroup)
```

```
$ python3 main.py 
Traceback (most recent call last):
  File "/mnt/dataint/data/progetti_miei/python/pybliometrics_bug/main.py", line 9, in <module>
    print(au.classificationgroup)
  File "/home/raffaele/.local/lib/python3.10/site-packages/pybliometrics/scopus/author_retrieval.py", line 66, in classificationgroup
    out = [(int(item['$']), int(item['@frequency'])) for item in
  File "/home/raffaele/.local/lib/python3.10/site-packages/pybliometrics/scopus/author_retrieval.py", line 66, in <listcomp>
    out = [(int(item['$']), int(item['@frequency'])) for item in
ValueError: invalid literal for int() with base 10: '2800;
```

**Comment by raffaem** [comment]
Both

`chained_get(self._profile, path, []))` and `listify(chained_get(self._profile, path, [])))` are list of dicts, so I wonder what the listify does here.

What do you think is the best way to fix this?

Deleting the ; seems impractical and too slow.

We could have a try ... except that does something more complicated in case of failure

**Comment by Michael-E-Rose** [comment]
The `listify()` assures we always receive a list here. If `chained_get(self._profile, path, []))` returns just single dictionary, as is the case for authors who work in just one subject area, `listify()` safely turns this into a list. I've also seen cases where two dictionaries were just bind together.

You caught a really weird mistake in the Scopus database. It's of the sort of "how can we make the life of users really complicated?"

Your solution is good but too complex. I'll respond there.

PS: It's not necessary to first create an issue and immediately a PR. You might as well create the PR and explain its reason right there. Might save you time and it's less complex.

**Comment by raffaem** [comment]
how do I post the code sample and the error message in the PR?

in a comment?

**Comment by Michael-E-Rose** [comment]
Yes. It behaves like an issue
