### ISSUE TITLE
Calling AuthorRetrieval with refresh=True fails to update method calls

### ISSUE THREAD

**Issue by astrochun** [pybliometrics-dev/pybliometrics#260]
pybliometrics version: 3.3.0

This problem occurs when attempting to update the Author record based on an `AuthorRetrieval` with `refresh=True`. The use of the `.get_documents()` does not trigger a new `ScopusSearch`. Thus, records can be outdated.

Code to reproduce the bug:
```
ar = AuthorRetrieval('9-s2.0-36621004800', view='ENHANCED', refresh=true)
ar.document_count  # 219
len(ar.get_documents()) #218
```

The difference is due to one new paper that appeared after the first caching.  Currently, the API requires providing `refresh=True`, which is not so obvious - took me a while to realize that the document search query did not update accordingly.

Expected behavior:
If certain arguments are set at the class level, they should be reflected in method calls to ensure that everything is in sync.

**Comment by Michael-E-Rose** [comment]
This is not a bug, this is at most unclear documentation. The documentation for [`AuthorRetrieval().get_documents()`](https://pybliometrics.readthedocs.io/en/stable/classes/AuthorRetrieval.html#pybliometrics.scopus.AuthorRetrieval.get_documents) states:

> Parameters
> args (str) – Parameters to be passed on to ScopusSearch().
> 
> kwds (str) – Parameters to be passed on to ScopusSearch().

Why is that not obvious?

**Comment by astrochun** [comment]
Hi @Michael-E-Rose, thanks for the response. The reason why it wasn't obvious is because I had thought `refresh` from the `AuthorRetrieval` was an instance variable, such that if I say `refresh=3`, any get methods would have those settings by default.

I suppose this is more of a feature than a bug for the default settings in the get methods to be consistent with input arguments when the object was created.

**Comment by Michael-E-Rose** [comment]
What about we add a note `Note: The class' `refresh` parameter is not used here.`?

**Comment by astrochun** [comment]
> What about we add a note `Note: The class' `refresh` parameter is not used here.`?

That would suffice.
