### ISSUE TITLE
Location of config and cache files

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#270]
The [XDG Base Directory](https://wiki.archlinux.org/title/XDG_Base_Directory) specification provides for:
- config files to be located in `XDG_CONFIG_HOME`, which should default to `$HOME/.config`
- cache files to be located in `XDG_CACHE_HOME`, which should default to `$HOME/.cache`

Can we move `config.ini` in `$HOME/.config/.pybliometrics`, and the cache in `$HOME/.cache/.pybliometrics`, and still read also from the old directory (`$HOME/.pybliometrics`) for backwards compatibility?

**Comment by Michael-E-Rose** [comment]
I'm sorry, I totally overlooked this issue. You are totally right, the XDG schemas should be the default paths. I changed it such that the old locations can still be used - this includes the very old location `~/.scopus/`.

The configuration file is henceforth going to be named `~/.config/pybliometrics.cfg`.
