### ISSUE TITLE
yearly data in SerialTitle()

### ISSUE THREAD

**Issue by otichy** [pybliometrics-dev/pybliometrics#272]
pybliometrics version: 3.4.0

Affected classes: pybliometrics.scopus.SerialTitle

Expected behavior: Currently, citescoreyearinfolist returns "A list of two tuples of the form (year, cite-score)". Is it possible to also retrieve other like percentCited and citeScoreSubjectRank/percentile? It would be good to be able to also get other than the two most recent years, as it is possible in pybliometrics.scopus.SerialSearch.

**Comment by Michael-E-Rose** [comment]
Unfortunately, `citescoreyearinfolist` contains just these two information as per Scopus. One for the last year, one for the ongoing year (the tracker year). That's also what the documentation explains.

BUT: I just saw that Scopus returns new information previously unused under the keyword "yearly_data". This includes the number of publications of this year, the share and count not cited, as well as the total citations to this journal this year. I'm going to add this later.

**Comment by otichy** [comment]
I am getting the yearly list via: https://api.elsevier.com/content/serial/title/issn/03781119?apiKey=7f59af901d2d86f78a1fd60c1bf9426a (as per https://dev.elsevier.com/scopus.html#!/Serial_Title/SerialTitleMetadata)

**Comment by Michael-E-Rose** [comment]
Yes, yearly data is available on the number of documents and the number and share of cited documents. But there is no yearly data for metrics (SNIP, SJR or CiteScore). For those things you should reach out to Scopus, maybe they include this one day.

**Comment by otichy** [comment]
But I am getting the yearly quartiles via the API in the json, you just need to use the citescore view like this:

https://api.elsevier.com/content/serial/title?issn=03781119&view=citescore&apiKey=7f59af901d2d86f78a1fd60c1bf9426a

It gives you the quartiles from 2011 until 2022.

**Comment by Michael-E-Rose** [comment]
Ach now I get this! It's in a different view. This view is not documented in https://dev.elsevier.com/sc_serial_title_views.html. I will have to familiarise myself with.

**Comment by otichy** [comment]
I noticed in documented here: https://dev.elsevier.com/documentation/SerialTitleAPI.wadl
But it is otherwise well hidden  :)

**Comment by Michael-E-Rose** [comment]
Implemented in fa24aeaf1e7ef621e4cbd58abb206301ebe5822f.
