### ISSUE TITLE
How to find 5000+ papers using ScopusSearch?

### ISSUE THREAD

**Issue by iriscxy** [pybliometrics-dev/pybliometrics#273]
I get the error `Found 811644 matches.  The query fails to return more than 5000 entries.  Change your query such that it returns fewer entries.`. However, I want to split the results and use different accounts to download them. What should I do?

**Comment by Michael-E-Rose** [comment]
Could you please ask this question on StackOverflow? GitHub issues are meant to report bugs and suggest features.
