### ISSUE TITLE
create_config(): Prompt is not skipped when there are keys

### ISSUE THREAD

**Issue by leoncena** [pybliometrics-dev/pybliometrics#274]
pybliometrics version:
3.4.0

Code to reproduce the bug:
```
import os
keys = ['aaaa', 'bbbb', 'cccc']
from pybliometrics.scopus.utils import create_config
create_config(keys=keys)
```

Expected behavior:

According to the documentation, the prompt should be skipped, if I understand it correctly. Unfortunately, this is not the case. Did I miss something or is this a bug?

**Comment by Michael-E-Rose** [comment]
I introduced these parameters last year in #245, but in fact they only work if `config.ini` does exist. If it does not exist, which is checked already while _importing_ any pybliometrics function, https://github.com/pybliometrics-dev/pybliometrics/blob/master/pybliometrics/scopus/utils/startup.py#L8 kicks in.

I will update the documentation just now.
