### ISSUE TITLE
Citing papers list does not match with the citedby_count

### ISSUE THREAD

**Issue by AndreaUnige** [pybliometrics-dev/pybliometrics#277]
pybliometrics version: 3.4.0

The citing papers list does not match with the _citedby_count_.

More precisely, if I run the code reported below I should get the list of all the citing papers for the paper identified with eid='2-s2.0-85084808560', which is actually a list of 25 articles. However, if the Scopus website is considered the results are different: the paper with eid='2-s2.0-85084808560' has 32 citations.

Namely, the list returned by my code only contains the first 25 papers, so the last 7 papers are missing.

This strange behavior occurs with several other papers while with many other the code runs smoothly meaning that list of citing papers is exactly the same with the citing papers present on the Scopus website. 

**Code to reproduce the bug:**
```
response = requests.get('https://api.elsevier.com/content/search/scopus',
                            params=f'apikey=MY_SECRET_KEY&query=refeid('2-s2.0-85084808560')',
                            timeout=30)
response = response.json()['search-results']['entry']
```

response is a list of 25 elements. It should contain the _citing papers_ (i.e., the papers which cite the paper with eid='2-s2.0-85084808560').
However, if you consider the Scopus platform the paper with eid='2-s2.0-85084808560' has 
Direct link: https://www.scopus.com/record/display.uri?eid=2-s2.0-85084808560&origin=resultslist&sort=plf-f&src=s&sid=4d7bac0cb873a9e6a826cbe36b09781b&sot=aut&sdt=a&sl=17&s=AU-ID%288546192900%29&relpos=18&citeCnt=32&searchTerm=

**Expected behavior:**
I expected a list of 32 elements which contains all the citing papers.

**Comment by AndreaUnige** [comment]
Just did some further study.
It seems that 25 is the number of items per page.

So the question becomes, how to get the results from the next page ?

**Comment by Michael-E-Rose** [comment]
PS: Please next time ask this kind of question (how to do xyz?) on StackOverflow.
