### ISSUE TITLE
How to use the Scopus Author Search API without InstToken?

### ISSUE THREAD

**Issue by pedroelias520** [pybliometrics-dev/pybliometrics#282]
It's been a few days since I've been trying to use the Scopus Authors API, but I always run into the problem of:

"The requestor is not authorized to access the requested view or fields of the resource"

I tried to understand why this was happening and I saw that it has something to do with the internet I am using, I already sent an email asking for an institutional token and I didn't get a response, I wanted to know if it is really necessary to access the institution's internet network for this.

**Comment by Michael-E-Rose** [comment]
Yes.

Scopus is an expensive database. You will not get an InstToken if your institution doesn't pay for the service.

You have to use an API key _and_ be in the network of an institution that subscribes to Scopus API. See https://pybliometrics.readthedocs.io/en/stable/access.html.

**Comment by Michael-E-Rose** [comment]
I think you want to contact Sales: https://www.elsevier.com/solutions/scopus/contact-sales
