### ISSUE TITLE
ModuleNotFoundError: No module named 'pybliometrics.scopus' with version 3.5.0

### ISSUE THREAD

**Issue by martinuray** [pybliometrics-dev/pybliometrics#284]
pybliometrics version: 3.5.0

Code to reproduce the bug:
```
$ pip install pybliometrics==3.5.0
$ python
>>> from pybliometrics.scopus import AbstractRetrieval
...
ModuleNotFoundError: No module named 'pybliometrics.scopus'
```

Expected behavior: not an exception

I tested it with version 3.4.0, here it works as expected.

**Comment by martinuray** [comment]
This works now. Thanks.

**Comment by Michael-E-Rose** [comment]
The problem was in fact just a missing wheel, and old information lingering in `pybliometrics.egg-info`.
