### ISSUE TITLE
Dependency missing in v3.5.1

### ISSUE THREAD

**Issue by maltevogl** [pybliometrics-dev/pybliometrics#285]
First of all: thanks for the great package! 

pybliometrics version: 3.5.1

Code to reproduce the bug: 
pip install -U pybliometrics, then run any search.

Expected behavior: 

Allow e.g. ScopusSearch

First search raises a missing dependency of SimpleJSON package. The pyproject.toml should contain the requirements, e.g. like this https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dependencies-optional-dependencies A simple install of the missing package solves the issue.

**Comment by Michael-E-Rose** [comment]
Yes I also stumbled over this. I thought the [requirements.txt](https://github.com/pybliometrics-dev/pybliometrics/blob/master/requirements.txt) would continue to be respected.

I will check however whether `simplejson` is still needed.
