### ISSUE TITLE
Not authorised to access resource, despite being connected to Universities network.

### ISSUE THREAD

**Issue by riddhis5** [pybliometrics-dev/pybliometrics#288]
pybliometrics version:

Code to reproduce the bug:
When running pybliometrics I am faced with the following issue:
The requestor is not authorized to access the requested view or fields of the resource.

I am on my Universities network, and have a subscription to Elsevier, however I am still faced with this error. Any help on this issue will be greatly appreciated.

This is the code that I am running:
from pybliometrics.scopus import AbstractRetrieval
ab = AbstractRetrieval("10.1097/EE9.0000000000000098")
ab.title

Expected behavior:
Return relevant information

**Comment by riddhis5** [comment]
Just to note, that I do want to use the litstudy package, which requires the use of pybliometrics.

**Comment by james-geiger** [comment]
Hi @riddhis5 --

I know that some universities authenticate through Elsevier using a single sign-on mechanism, and not through a proxy, which can complicate authentication to the API.

Personally, I have to use an Insttoken even though I am on the network using a University device.  You might have some luck reaching out to Elsevier support.

**Comment by riddhis5** [comment]
Hello, 
Thanks for your response. I was using Google Colab to run my code, which is the reason as to why the code was producing a bug. When running the code using Jupyter Notebook, the issue was fixed.

**Comment by james-geiger** [comment]
@riddhis5 Glad to year you got it figured out!  Theoretically, you could run the code in Google Colab, but you'd definitely need an Insttoken at that point.

Also, not sure how well the caching functionality would work in the cloud, which might inadvertently use up your request allotment.
