### ISSUE TITLE
add backticks into docstring (documentation)

### ISSUE THREAD

**Issue by jpcaveiro** [pybliometrics-dev/pybliometrics#289]
pybliometrics version: 3.5.2

Affected classes: AbstractRetrieval(Retrieval)

Expected behavior:   Add backticks to description like `description`, and the same for abstract in a similar docstring, because "property description" could mean several things. 

```
"""The abstract of a document.
Note: If this is empty, try property description instead.
"""
```

**Comment by Michael-E-Rose** [comment]
That's correct! Do you want to tackle this in a PR?

**Comment by nils-herrmann** [comment]
Integration of backticks into docstring should be complete.

**Comment by Michael-E-Rose** [comment]
Commit b7a2ec61eea3fcd8ccc5da1d442837a0fd280020
