### ISSUE TITLE
ScopusSearch by DOI produces different results if space added

### ISSUE THREAD

**Issue by hyper94** [pybliometrics-dev/pybliometrics#299]
pybliometrics version: 3.5.2

Using scopus.ScopusSearch(DOI()). Adding a space after "DOI(" returns the correct results, if no space is added, a None is returned.

Code to reproduce the bug:
```
doi = "10.1093/restud/rdac058"
print(pybliometrics.scopus.ScopusSearch(f"DOI({doi})").results) # This returns a None
print(pybliometrics.scopus.ScopusSearch(f"DOI( {doi})").results) # Notice space after parenthesis, this works

```

**Comment by Michael-E-Rose** [comment]
For me both work. And I can't think of a reason why it wouldn't. pybliometrics passes on the search query to Scopus: as long as it works there, it works via pybliometrics.

Try this on your system:

```
doi = "10.1093/restud/rdac058"
s = pybliometrics.scopus.ScopusSearch(f"DOI({doi})")
print(s.get_cache_file_age())
```

Then do this:
```
doi = "10.1093/restud/rdac058"
s = pybliometrics.scopus.ScopusSearch(f"DOI({doi})", refresh=True)
print(s.results)
```

**Comment by hyper94** [comment]
Thanks a lot! refresh = True solves the issue, which was indeed relevant only for old search queries.
