### ISSUE TITLE
What is the Scopus search link?

### ISSUE THREAD

**Issue by Gautamshahi** [pybliometrics-dev/pybliometrics#305]
I want to verify the result obtained from the pybliometrics with a manual search, but I am not getting the link for a manual search. 

Can you please share the link where I can search manually based on title, abstract etc?

**Comment by Michael-E-Rose** [comment]
Are you looking for https://www.scopus.com/?

**Comment by Gautamshahi** [comment]
Thank you for your reply; not where we can put some string for search based on title, keywords,abstract; even after institutional access, I am not able to get the page.

Example - I can see the option to search an author but not a publication

https://www.scopus.com/freelookup/form/author.uri?zone=TopNavBar&origin=NO%20ORIGIN%20DEFINED

**Comment by Michael-E-Rose** [comment]
Well, then you probably don't have the subscription to access Scopus. Please refer to https://pybliometrics.readthedocs.io/en/stable/access.html#how-to-access-scopus
