### ISSUE TITLE
'ENTITLED' view is not supported

### ISSUE THREAD

**Issue by nils-herrmann** [pybliometrics-dev/pybliometrics#308]
pybliometrics version: 3.8

Affected classes: AbstractRetrieval, AffiliationRetrieval, AuthorRetrieval

Expected behaviour: Scopus has a view called `'ENTITLED'` to query if the requestor is entitles to access the requested resource. pybliometrics. For the sake of completeness the view could be added. Nevertheless it does not really contain interesting information, e.g.:

{‘document-entitlement': {'message': 'Requestor is entitled to the requested resource',
  'url': 'http://prod-app-internal.elsapi.elsst.com/ElsApi/content/abstract/doi/10.1016/bs.agph.2021.06.003',
  'status': 'ENTITLED'}}

**Comment by Michael-E-Rose** [comment]
Then let's implement this. What does it return actually, just this, the status?

**Comment by nils-herrmann** [comment]
Yes, it only returns the status.
