### ISSUE TITLE
Move creating folder from `get_folder()` to `init()`

### ISSUE THREAD

**Issue by nils-herrmann** [pybliometrics-dev/pybliometrics#316]
pybliometrics version: 3.8

Affected classes: All

Expected behavior: `init()` should create folders not `get_folder()`

**Comment by nils-herrmann** [comment]
Here some comments:
- The `init()` function checks if the config file has all the needed paths, if not the missing paths get written to the config file
- The `get_folder()` function was moved to the `startup.py` file
- The `CONFIG_DIR` variable and `get_config_path()` function were removed.

**Comment by Michael-E-Rose** [comment]
PR #317 merged
