### ISSUE TITLE
CitationOverview's cc property unexpected Error.

### ISSUE THREAD

**Issue by kosh-jp** [pybliometrics-dev/pybliometrics#322]
pybliometrics version:
3.6

Code to reproduce the bug:
Errors are occurring in specific doi.
10.11604/pamj.2015.22.35.6737

It is similar to this issue. https://github.com/pybliometrics-dev/pybliometrics/issues/301

#### code
```
doi = "10.11604/pamj.2015.22.35.6737"

co = CitationOverview(
    [doi],
    2013,
    id_type="doi",
    APIKey=SCOPUS_API_KEY,
    InstToken=SCOPUS_INST_TOKEN,
)

print(co.cc[0])
```
#### result
```
...
  File "/mydir/env/lib/python3.10/site-packages/pybliometrics/scopus/abstract_citation.py", line 48, in cc
    cites = [int(d["$"]) for d in doc["cc"]]
KeyError: 'cc'
```
Maybe, cc is not return from scopus API.
```
'_citeInfoMatrix': [
	{
		"@_fa": "true",
		"identifier": "SCOPUS_ID:84973517467",
		"url": "https://api.elsevier.com/content/abstract/scopus_id/84973517467",
		"pcc": "0",
		"lcc": "0",
		"rangeCount": "0",
		"rowTotal": "0"
	}
]
```

**Comment by Michael-E-Rose** [comment]
According to the [Scopus search](https://www.scopus.com/results/results.uri?sort=plf-f&src=s&st1=10.11604%2Fpamj.2015.22.35.6737&sid=8ed366a64b83c6c15c63ba0f95386365&sot=b&sdt=b&sl=34&s=DOI%2810.11604%2Fpamj.2015.22.35.6737%29&origin=searchbasic&editSaveSearch=&yearFrom=Before+1960&yearTo=Present&sessionSearchId=8ed366a64b83c6c15c63ba0f95386365&limit=10), this DOI belongs to EID 2-s2.0-84973517467 - but it apparently doesn't exist! See here: https://www.scopus.com/record/display.uri?eid=2-s2.0-84973517467&origin=resultslist

So the Scopus API should actually return 404. It's a problem in the Scopus database, which should be reported.

I value tremendously when people come up with a PR, but in this case I am hesitant to accept it. The PR would cover an apparent mistake in the Scopus database.

**Comment by astrochun** [comment]
I have a similar issue with another record, 85185347473. However, upon reviewing it, it seems that the record exists:
```python
{'@_fa': 'true', 'identifier': 'SCOPUS_ID:85185347473', 'url': 'https://api.elsevier.com/content/abstract/scopus_id/85185347473', 'pcc': '0', 'lcc': '0', 'rangeCount': '0', 'rowTotal': '0'}
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
...
     44 try:
---> 45     cites = [int(d['$']) for d in doc['cc']]
     46 except AttributeError:  # No citations
     47     cites = [0]*len(_years)

KeyError: 'cc'
```

https://www.scopus.com/record/display.uri?eid=2-s2.0-85185347473&origin=resultslist

**Comment by Michael-E-Rose** [comment]
Interesting case: Scopus.com says, the article actually was cited. I wonder whether this is a bug in scopus? Because the other keys in the citation matrix are present, and 0. Anyways, going over these kind of inconsistencies and irregularities in the Scopus API is the job of pybliometrics ^^

**Comment by Michael-E-Rose** [comment]
Let's hope this solves it

**Comment by astrochun** [comment]
> Let's hope this solves it

Thanks. I'll wait for a new PyPI release to pull and try it out.
