### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#339]
It looks like pybliometrics is not able to rotate between API keys anymore.

I receive an "invalid API key" error, but if I edit the config file and append the first API key to the end of the list, it works again (thus using what was the second API key)

**Comment by Michael-E-Rose** [comment]
That happens when a key is depleted? @raffaem is this also what you get when you use your depleted key?

**Comment by Michael-E-Rose** [comment]
I have tested this with my keys on the Abstract Retrieval API. The automatic key swap works fine and as expected.
How is it going for your @raffaem ?
