### ISSUE TITLE
Query fails to return more than 5000 entries

### ISSUE THREAD

**Issue by bmht** [pybliometrics-dev/pybliometrics#345]
Code to Reproduce the Bug:
response = AuthorSearch("AF-ID(60019722) AND SUBJAREA(COMP)")

Error Encountered:
"Found 11,179 matches. The query fails to return more than 5000 entries. Please modify your query to return fewer entries."

Issue Description:
I aim to obtain a list of authors who have published more than 10 articles from this university. However, it's evident that the entries exceed 5000. To reduce the number of entries, I filtered by subject area, attempting to keep it under 5000, but there are still more than 5000 entries. I'm unsure what to do next. I tried increasing the count parameter, allowing me to specify the number of articles returned each time and then gradually increase it:
AuthorSearch("AF-ID(60019722) AND SUBJAREA(COMP) AND count({count from 10 to ...})")
I realize this approach is inefficient and time-consuming, so I'm asking if anyone has a better method to achieve this goal. Thanks in advance.

Additional Context:
The same analysis will also be applied to 100 other universities.

**Comment by Michael-E-Rose** [comment]
Go by year.

**Comment by bmht** [comment]
> 按年份去。



> Go by year.

Thanks for you reply.
