### ISSUE TITLE
(Draft) ScienceDirect: Object Retrieval API

### ISSUE THREAD

**Issue by nils-herrmann** [pybliometrics-dev/pybliometrics#353]
Research for the implementation of the ScienceDirect: [Object Retrieval API](https://dev.elsevier.com/documentation/ObjectRetrievalAPI.wadl). The description of the API states: These interfaces represent retrieval of objects associated with a full text article. This resource can also return reference details for an individual object or an entire full text article. The reference metadata response will contain links to the associated [Full-Text article](https://dev.elsevier.com/documentation/FullTextRetrievalAPI.wadl).

**Comment by nils-herrmann** [comment]
The Object Retrieval API returns different things depending on the query:
- Object references of a document
- A specific object
- A thumbnail image
- A regular-sized image
- A high resolution image

So there is a design decision to make. Do we want the ObjectRetrieval Class to:
- Have **one** `results` property (With a different result depending on the query type)
- Have **multiple** properties, each representing a query type

What do you think @Michael-E-Rose ?

**Comment by Michael-E-Rose** [comment]
We had such a case before, with the `SerialSearch()` and the `SerialTitle()` classes which both access the [Serial Title API](https://dev.elsevier.com/documentation/SerialTitleAPI.wadl). That API has a search part and a retrieval part, so we created two classes. I'm thinking about the same for this class. However, we might put the three image retrieval classes together and handle the quality of the image via view. Could you please check whether the return values of the three image access points are (almost) the same?

**Comment by nils-herrmann** [comment]
Implementing two classes (1 for metadata and 1 for the objects) is a good idea.

Regarding the images:
- There are 3 image views (`STANDARD`,`THUMBNAIL` , `HIGH`)
- `STANDARD` is always available 
- `THUMBNAIL` , `HIGH are not always available

**Comment by nils-herrmann** [comment]
For sake of documenting: I'm having some trouble with the retrieval of .svg objects. In the [file attached](https://github.com/user-attachments/files/16934035/questions.pdf) the problem is exemplified with two questions:
1. Why do I get a 404 when retrieving .svg objects?
2. Why does the metadata returns the mime type 'image/svg+xml' although it cannot be found on the documentation.

**Comment by Michael-E-Rose** [comment]
Scopus doesn't maintain its documentation well. There are things in the API but not in the documentation, and vice versa. So, don't investigate the issue too much; pybliometrics can go without svg if needed.

**Comment by nils-herrmann** [comment]
This draft resulted in two issues: #355 and #360
