### ISSUE TITLE
Can it also include " scopus_id " in the output of Scopus Search?

### ISSUE THREAD

**Issue by dru1889** [pybliometrics-dev/pybliometrics#359]
pybliometrics version: 4.1

Affected classes: ScopusSearch() function

Expected behavior: Output "Scopus_id" in the results list.

**Comment by Michael-E-Rose** [comment]
No, because Scopus doesn't provide this information. The lost is items they provide is https://dev.elsevier.com/sc_search_views.html.

**Comment by dru1889** [comment]
Hi Michael, Thanks for your reply, I checked the link you provided. And find the Scopus ID is provided in the list as:

![image](https://github.com/user-attachments/assets/052bdd24-751e-436d-832d-7cbbcaf0dcd1)

**Comment by Michael-E-Rose** [comment]
Yes you're right! Sorry, I mixed things up.

I think the reason why we opted to skip the Scopus UD here is that it's embedded in the EID. Just take the part after the last hyphen and you have your ID.
