### ISSUE TITLE
Count parameter not working

### ISSUE THREAD

**Issue by DataGomes** [pybliometrics-dev/pybliometrics#361]
pybliometrics version: 4.1

Code to reproduce the bug:
import pybliometrics
pybliometrics.scopus.init() 
from pybliometrics.scopus import ScopusSearch
s = ScopusSearch('artificial AND intelligence AND genetics AND research AND healthcare', count = 10, view = "COMPLETE")

Expected behavior:

The expected behavior would be to limit the results to only 10, however it is not doing that.

**Comment by Michael-E-Rose** [comment]
Please don't file an issue here if the same question is on [StackOverflow](https://stackoverflow.com/questions/79132188/count-parameter-not-working-in-pybliometrics).
