### ISSUE TITLE
Can I get subject areas via ScopusSearch, or just AbstractRetrieval?

### ISSUE THREAD

**Issue by PhanTask** [pybliometrics-dev/pybliometrics#363]
Hello, thanks for developing this super cool library! I have a question regarding subject areas.

I noticed that there are no subject areas for the articles retrieved through ScopusSearch, and it seems I have to use other APIs such as AbstractRetrieval to get subject areas for each article through its identifier.

The fact is that I have retrieved tons of articles through ScopusSearch (say, articles in the past 10 years. I can finish the search by using <10 API keys), but it seems it would require way more tons of quota to call AbstractRetrieval for each paper to get the subject areas (I have run out of 40 API keys but could not finish even two years).

I wonder if there are any better ways or suggestions? Thanks!

**Comment by Michael-E-Rose** [comment]
That's a question for StackOverflow. Please ask the question there and tag [#pybliometrics](https://stackoverflow.com/questions/tagged/pybliometrics).
