### ISSUE TITLE
Remove `typing.Type`

### ISSUE THREAD

**Issue by nils-herrmann** [pybliometrics-dev/pybliometrics#370]
Since python 3.9 `typing.Type` is [depreciated](https://peps.python.org/pep-0585/).

**Comment by Michael-E-Rose** [comment]
Oh but we will continue to support Python 3.9 until its end-of-life - that's gonna be May next year. So until then we need to keep the `Type[]`.

**Comment by nils-herrmann** [comment]
Then let's wait until then.
